version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: refactorizacion-gdl-app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - refactorizacion-gdl

  nginx:
    image: nginx:alpine
    container_name: refactorizacion-gdl-nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - refactorizacion-gdl

  db:
    image: postgres:17-alpine
    container_name: refactorizacion-gdl-db
    restart: unless-stopped
    environment:
      POSTGRES_DATABASE: ${DB_DATABASE}
      POSTGRES_ROOT_PASSWORD: ${DB_PASSWORD}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - refactorizacion-gdl

  redis:
    image: redis:alpine
    container_name: refactorizacion-gdl-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - refactorizacion-gdl

networks:
  refactorizacion-gdl:
    driver: bridge

volumes:
  dbdata:
    driver: local