-- Script de despliegue de SPs faltantes
-- Módulo: Padrón Licencias
-- Fecha: 2025-11-11
-- Total SPs: 185

\cd C:/Sistemas/RefactorX/Guadalajara/RecodePHP/GDL/RefactorX/Base/padron_licencias/database/database

\i empresasfrm_empresas_estadisticas.sql
\i empresasfrm_empresas_list.sql
\i empresasfrm_empresas_create.sql
\i empresasfrm_empresas_update.sql
\i empresasfrm_empresas_delete.sql
\i estatusfrm_estatusfrm_sp_get_revision_info.sql
\i estatusfrm_estatusfrm_sp_get_historial_estatus.sql
\i CatRequisitos_catrequisitos_list.sql
\i CatRequisitos_catrequisitos_create.sql
\i CatRequisitos_catrequisitos_update.sql
\i CatRequisitos_catrequisitos_delete.sql
\i LigaRequisitos_ligarequisitos_giros.sql
\i LigaRequisitos_ligarequisitos_available.sql
\i LigaRequisitos_ligarequisitos_list.sql
\i LigaRequisitos_ligarequisitos_add.sql
\i LigaRequisitos_ligarequisitos_remove.sql
\i RegistroSolicitud_registro_solicitud.sql
\i RegistroSolicitud_agregar_documento.sql
\i ReactivaTramite_get_giro_by_id.sql
\i BloquearAnunciorm_bloquearanuncio_get_anuncio.sql
\i BloquearAnunciorm_bloquearanuncio_get_bloqueos.sql
\i BloquearAnunciorm_bloquearanuncio_bloquear.sql
\i BloquearAnunciorm_bloquearanuncio_desbloquear.sql
\i BloquearLicenciafrm_bloquearlicencia_get_licencia.sql
\i BloquearLicenciafrm_bloquearlicencia_get_bloqueos.sql
\i BloquearLicenciafrm_bloquearlicencia_bloquear.sql
\i BloquearLicenciafrm_bloquearlicencia_desbloquear.sql
\i BloquearTramitefrm_bloqueartramite_get_tramite.sql
\i BloquearTramitefrm_bloqueartramite_get_bloqueos.sql
\i BloquearTramitefrm_bloqueartramite_get_giro.sql
\i BloquearTramitefrm_bloqueartramite_bloquear.sql
\i BloquearTramitefrm_bloqueartramite_desbloquear.sql
\i CatalogoActividadesFrm_catalogo_actividades_list.sql
\i CatalogoActividadesFrm_catalogo_actividades_create.sql
\i CatalogoActividadesFrm_catalogo_actividades_update.sql
\i CatalogoActividadesFrm_catalogo_actividades_delete.sql
\i Cruces_cruces_search_calle1.sql
\i Cruces_cruces_search_calle2.sql
\i Cruces_cruces_localiza_calle.sql
\i DetalleLicencia_get_saldo_licencia.sql
\i GirosDconAdeudofrm_giros_dcon_adeudo.sql
\i GruposLicenciasAbcfrm_list_grupos_licencias.sql
\i GruposLicenciasAbcfrm_insert_grupo_licencia.sql
\i GruposLicenciasAbcfrm_update_grupo_licencia.sql
\i GruposLicenciasAbcfrm_delete_grupo_licencia.sql
\i Hastafrm_validate_hasta_form.sql
\i ImpLicenciaReglamentada_implicenciareglamentada_sp_get_license_data.sql
\i ImpLicenciaReglamentada_implicenciareglamentada_sp_print_license.sql
\i ImpLicenciaReglamentadaFrm_get_licencia_reglamentada.sql
\i ImpLicenciaReglamentadaFrm_check_licencia_bloqueada.sql
\i ImpLicenciaReglamentadaFrm_calcular_adeudo_licencia.sql
\i ImpLicenciaReglamentadaFrm_detalle_saldo_licencia.sql
\i ImpOficiofrm_get_tramite_info.sql
\i ImpOficiofrm_imp_oficio_tramite_info.sql
\i ImpOficiofrm_imp_oficio_register.sql
\i ImpRecibofrm_buscar_licencia.sql
\i ImpRecibofrm_get_licencia_recibo.sql
\i ImpRecibofrm_get_parametros_recibo.sql
\i ImpRecibofrm_numero_a_letras.sql
\i LicenciasVigentesfrm_LicenciasVigentesfrm_sp_stats.sql
\i Propuestatab_get_cuenta_historico.sql
\i Propuestatab_get_predial_historico.sql
\i Propuestatab_get_ubicacion_historico.sql
\i Propuestatab_get_valores_historico.sql
\i Propuestatab_get_diferencias_historico.sql
\i Propuestatab_get_regimen_propiedad_historico.sql
\i ReporteAnunExcelfrm_reporte_anuncios_excel.sql
\i SGCv2_sgcv2_sp_get_quality_indicators.sql
\i SGCv2_sgcv2_sp_get_processes.sql
\i SGCv2_sgcv2_sp_save_process.sql
\i Semaforo_semaforo_get_random_color.sql
\i Semaforo_semaforo_register_color_result.sql
\i Semaforo_semaforo_save.sql
\i Semaforo_semaforo_get_stats.sql
\i Semaforo_semaforo_history.sql
\i TDMConection_tdmconection_sp_get_connection_status.sql
\i TDMConection_tdmconection_sp_get_sync_log.sql
\i TDMConection_tdmconection_sp_sync_tramites.sql
\i ZonaAnuncio_zonaanuncio_list.sql
\i ZonaAnuncio_zonaanuncio_create.sql
\i ZonaAnuncio_zonaanuncio_update.sql
\i ZonaAnuncio_zonaanuncio_delete.sql
\i ZonaLicencia_get_recaudadoras.sql
\i ZonaLicencia_get_zonas.sql
\i ZonaLicencia_get_subzonas.sql
\i ZonaLicencia_get_licencia.sql
\i ZonaLicencia_save_licencias_zona.sql
\i bajaAnunciofrm_baja_anuncio_buscar.sql
\i bajaAnunciofrm_verifica_firma.sql
\i bajaAnunciofrm_baja_anuncio_procesar.sql
\i bajaLicenciafrm_consulta_licencia.sql
\i bajaLicenciafrm_consulta_anuncios_licencia.sql
\i bajaLicenciafrm_verifica_firma.sql
\i bajaLicenciafrm_baja_licencia.sql
\i bloqueoDomiciliosfrm_bloqueodomicilios_update.sql
\i bloqueoDomiciliosfrm_bloqueodomicilios_list.sql
\i bloqueoDomiciliosfrm_bloqueodomicilios_create.sql
\i bloqueoDomiciliosfrm_bloqueodomicilios_cancel.sql
\i bloqueoRFCfrm_bloqueorfc_list.sql
\i bloqueoRFCfrm_bloqueorfc_buscar_tramite.sql
\i bloqueoRFCfrm_bloqueorfc_create.sql
\i bloqueoRFCfrm_bloqueorfc_desbloquear.sql
\i busque_busque_search_by_owner.sql
\i busque_busque_search_by_location.sql
\i busque_busque_search_by_account.sql
\i busque_busque_search_by_rfc.sql
\i busque_busque_search_by_cadastral_key.sql
\i busque_busque_get_detail.sql
\i cartonva_get_cuenta_by_cvecuenta.sql
\i cartonva_get_convcta_by_cvecuenta.sql
\i cartonva_get_convcta_by_cvecatnva_subpredio.sql
\i cartonva_get_cartografia_predial.sql
\i catalogogirosfrm_catalogogiros_estadisticas.sql
\i catalogogirosfrm_catalogogiros_list.sql
\i catalogogirosfrm_catalogogiros_get.sql
\i catalogogirosfrm_catalogogiros_create.sql
\i catalogogirosfrm_catalogogiros_update.sql
\i catalogogirosfrm_catalogogiros_cambiar_vigencia.sql
\i consAnun400frm_cons_anun_400_frm_get_anuncio_400.sql
\i consAnun400frm_cons_anun_400_frm_get_pagos_anun_400.sql
\i consLic400frm_cons_lic_400_frm_get_lic_400.sql
\i consLic400frm_cons_lic_400_frm_get_pago_lic_400.sql
\i constanciaNoOficialfrm_solicnooficial_list.sql
\i constanciaNoOficialfrm_solicnooficial_create.sql
\i constanciaNoOficialfrm_solicnooficial_update.sql
\i constanciaNoOficialfrm_solicnooficial_cancel.sql
\i dictamenfrm_dictamenes_estadisticas.sql
\i dictamenfrm_dictamenes_list.sql
\i dictamenfrm_dictamenes_create.sql
\i dictamenfrm_dictamenes_update.sql
\i dictamenusodesuelo_list_constancias.sql
\i dictamenusodesuelo_create_constancia.sql
\i dictamenusodesuelo_update_constancia.sql
\i dictamenusodesuelo_cancel_constancia.sql
\i firma_firma_save.sql
\i firma_firma_validate.sql
\i firmausuario_validate_firma_usuario.sql
\i formabuscolonia_listar_colonias.sql
\i formabuscolonia_buscar_colonias.sql
\i formabuscolonia_obtener_colonia_seleccionada.sql
\i formabuscalle_listar_calles.sql
\i formabuscalle_buscar_calles.sql
\i formatosEcologiafrm_get_tramites_by_fecha.sql
\i formatosEcologiafrm_get_tramite_by_id.sql
\i formatosEcologiafrm_get_cruce_calles_by_tramite.sql
\i frmImpLicenciaReglamentada_frmimplicenciareglamentada_sp_get_licencia_reglamentada_by_id.sql
\i frmselcalle_frmselcalle_get_calles.sql
\i frmselcalle_frmselcalle_get_calle_by_ids.sql
\i girosVigentesCteXgirofrm_girosVigentesCteXgirofrm_sp_get_catalogo_giros.sql
\i grs_dlg_grs_dlg_sp_get_giros.sql
\i grs_dlg_grs_dlg_sp_search_giros.sql
\i ligaAnunciofrm_buscar_anuncio.sql
\i ligaAnunciofrm_buscar_licencia.sql
\i ligaAnunciofrm_buscar_empresa.sql
\i ligaAnunciofrm_ligar_anuncio.sql
\i modtramitefrm_get_tramite_by_id.sql
\i modtramitefrm_get_giro_by_id.sql
\i modtramitefrm_update_tramite.sql
\i modtramitefrm_get_giros_search.sql
\i modtramitefrm_get_calles_search.sql
\i prepagofrm_prepago_get_data.sql
\i prepagofrm_prepago_get_ultimo_requerimiento.sql
\i prepagofrm_prepago_calcular_descpred.sql
\i prepagofrm_prepago_recalcular_dpp.sql
\i prepagofrm_prepago_liquidacion_parcial.sql
\i prepagofrm_prepago_eliminar_dpp.sql
\i prophologramasfrm_c_contribholog_list.sql
\i prophologramasfrm_c_contribholog_create.sql
\i prophologramasfrm_c_contribholog_update.sql
\i prophologramasfrm_c_contribholog_delete.sql
\i psplash_psplash_get_user_info.sql
\i psplash_psplash_get_announcements.sql
\i psplash_psplash_get_stats.sql
\i repdoc_repdoc_get_giros.sql
\i repdoc_repdoc_get_requisitos_by_giro.sql
\i repdoc_repdoc_print_permisos_eventuales.sql
\i repdoc_repdoc_print_requisitos.sql
\i repestado_get_tramite_estado.sql
\i repestado_get_tramite_revisiones.sql
\i sfrm_chgpass_sfrm_chgpass_sp_validate_current.sql
\i sfrm_chgpass_sfrm_chgpass_sp_update.sql
\i sfrm_chgpass_sfrm_chgpass_sp_bitacora.sql
\i webBrowser_webbrowser_sp_get_bookmarks.sql
\i webBrowser_webbrowser_sp_save_bookmark.sql
\i webBrowser_webbrowser_sp_delete_bookmark.sql

-- Verificar despliegue
SELECT COUNT(*) as sps_desplegados
FROM pg_proc p
JOIN pg_namespace n ON p.pronamespace = n.oid
WHERE n.nspname IN ('padron_licencias', 'comun', 'public')
  AND p.proname LIKE 'sp_%'
  OR p.proname LIKE '%frm%'
  OR p.proname LIKE '%_list'
  OR p.proname LIKE '%_create'
  OR p.proname LIKE '%_update'
  OR p.proname LIKE '%_delete';
