import { createRouter, createWebHistory } from 'vue-router'
import { setupGlobalGuards } from './guards'
import MainLayout from '@/components/layout/MainLayout.vue'

const router = createRouter({
  history: createWebHistory(import.meta.env.BASE_URL),
  routes: [
    {
      path: '/',
      name: 'dashboard',
      component: () => import('@/views/Dashboard.vue'),
      meta: { requiresAuth: false }
    },
    {
      path: '/login',
      name: 'login',
      component: () => import('@/views/Login.vue'),
      meta: { requiresAuth: false }
    },
// ESTACIONAMIENTO PUBLICO - Rutas con layout (nested routes)
{
  path: '/estacionamiento-publico',
  component: MainLayout,
  children: [
    { path: '', name: 'estacionamiento-publico', component: () => import('@/views/modules/estacionamiento_publico/index.vue') },
    { path: 'consulta', name: 'estacionamiento-publico-consulta', component: () => import('@/views/modules/estacionamiento_publico/ConsultaPublicos.vue') },
    { path: 'transacciones', name: 'estacionamiento-publico-transacciones', component: () => import('@/views/modules/estacionamiento_publico/TransPublicos.vue') },
    { path: 'actualizacion', name: 'estacionamiento-publico-actualizacion', component: () => import('@/views/modules/estacionamiento_publico/ActualizacionPublicos.vue') },
    { path: 'nuevo', name: 'estacionamiento-publico-nuevo', component: () => import('@/views/modules/estacionamiento_publico/PublicosNew.vue') },
    { path: 'reportes', name: 'estacionamiento-publico-reportes', component: () => import('@/views/modules/estacionamiento_publico/ReportesPublicos.vue') },
    { path: 'admin', name: 'estacionamiento-publico-admin', component: () => import('@/views/modules/estacionamiento_publico/AdminPublicos.vue') },
    { path: 'bajas', name: 'estacionamiento-publico-bajas', component: () => import('@/views/modules/estacionamiento_publico/BajasPublicos.vue') },
    { path: 'generar', name: 'estacionamiento-publico-generar', component: () => import('@/views/modules/estacionamiento_publico/GenerarPublicos.vue') },
    { path: 'pagos', name: 'estacionamiento-publico-pagos', component: () => import('@/views/modules/estacionamiento_publico/PagosPublicos.vue') },
    { path: 'info', name: 'estacionamiento-publico-info', component: () => import('@/views/modules/estacionamiento_publico/InfoPublicos.vue') },
    { path: 'listados', name: 'estacionamiento-publico-listados', component: () => import('@/views/modules/estacionamiento_publico/ListadosPublicos.vue') },
    { path: 'estadisticas', name: 'estacionamiento-publico-estadisticas', component: () => import('@/views/modules/estacionamiento_publico/EstadisticasPublicos.vue') },
    { path: 'conciliacion', name: 'estacionamiento-publico-conciliacion', component: () => import('@/views/modules/estacionamiento_publico/ConciBanortePublicos.vue') },
    { path: 'edocta', name: 'estacionamiento-publico-edocta', component: () => import('@/views/modules/estacionamiento_publico/EdoCtaPublicos.vue') },
    { path: 'reporte-lista', name: 'estacionamiento-publico-reporte-lista', component: () => import('@/views/modules/estacionamiento_publico/ReporteListaPublicos.vue') },
    { path: 'reporte-pagos', name: 'estacionamiento-publico-reporte-pagos', component: () => import('@/views/modules/estacionamiento_publico/ReportePagosPublicos.vue') },
    { path: 'reporte-folios', name: 'estacionamiento-publico-reporte-folios', component: () => import('@/views/modules/estacionamiento_publico/ReporteFoliosPublicos.vue') },
    { path: 'estado-mpio', name: 'estacionamiento-publico-estado-mpio', component: () => import('@/views/modules/estacionamiento_publico/EstadoMpioPublicos.vue') },
    { path: 'trans-folios', name: 'estacionamiento-publico-trans-folios', component: () => import('@/views/modules/estacionamiento_publico/TransFoliosPublicos.vue') },
    { path: 'up-pagos', name: 'estacionamiento-publico-up-pagos', component: () => import('@/views/modules/estacionamiento_publico/UpPagosPublicos.vue') },
    { path: 'valet-paso', name: 'estacionamiento-publico-valet-paso', component: () => import('@/views/modules/estacionamiento_publico/ValetPasoPublicos.vue') },
    { path: 'passwords', name: 'estacionamiento-publico-passwords', component: () => import('@/views/modules/estacionamiento_publico/PasswordsPublicos.vue') },
    { path: 'gen-arc-altas', name: 'estacionamiento-publico-gen-arc-altas', component: () => import('@/views/modules/estacionamiento_publico/GenArcAltasPublicos.vue') },
    { path: 'gen-arc-diario', name: 'estacionamiento-publico-gen-arc-diario', component: () => import('@/views/modules/estacionamiento_publico/GenArcDiarioPublicos.vue') },
    { path: 'gen-individual', name: 'estacionamiento-publico-gen-individual', component: () => import('@/views/modules/estacionamiento_publico/GenIndividualPublicos.vue') },
    { path: 'gen-pgos-banorte', name: 'estacionamiento-publico-gen-pgos-banorte', component: () => import('@/views/modules/estacionamiento_publico/GenPgosBanortePublicos.vue') },
    { path: 'reactiva-folios', name: 'estacionamiento-publico-reactiva-folios', component: () => import('@/views/modules/estacionamiento_publico/ReactivaFoliosPublicos.vue') },
    { path: 'cons-gral', name: 'estacionamiento-publico-cons-gral', component: () => import('@/views/modules/estacionamiento_publico/ConsGralPublicos.vue') },
    { path: 'cons-remesas', name: 'estacionamiento-publico-cons-remesas', component: () => import('@/views/modules/estacionamiento_publico/ConsRemesasPublicos.vue') },
    { path: 'aplica-pago-divadmin', name: 'estacionamiento-publico-aplica-pago-divadmin', component: () => import('@/views/modules/estacionamiento_publico/AplicaPagoDivAdminPublicos.vue') },
    { path: 'relacion-folios', name: 'estacionamiento-publico-relacion-folios', component: () => import('@/views/modules/estacionamiento_publico/RelacionFoliosPublicos.vue') },
    { path: 'imp-padron', name: 'estacionamiento-publico-imp-padron', component: () => import('@/views/modules/estacionamiento_publico/ImpPadronPublicos.vue') },
    { path: 'metrometers', name: 'estacionamiento-publico-metrometers', component: () => import('@/views/modules/estacionamiento_publico/MetrometersPublicos.vue') },
    { path: 'aspecto', name: 'estacionamiento-publico-aspecto', component: () => import('@/views/modules/estacionamiento_publico/AspectoPublicos.vue') },
    { path: 'autoriz-descto', name: 'estacionamiento-publico-autoriz-descto', component: () => import('@/views/modules/estacionamiento_publico/ChgAutorizDesctoPublicos.vue') },
    { path: 'contrarecibos', name: 'estacionamiento-publico-contrarecibos', component: () => import('@/views/modules/estacionamiento_publico/ContrarecibosPublicos.vue') },
    { path: 'mensaje', name: 'estacionamiento-publico-mensaje', component: () => import('@/views/modules/estacionamiento_publico/MensajePublicos.vue') },
    { path: 'folios-alta', name: 'estacionamiento-publico-folios-alta', component: () => import('@/views/modules/estacionamiento_publico/FoliosAltaPublicos.vue') },
    { path: 'carga-edoex', name: 'estacionamiento-publico-carga-edoex', component: () => import('@/views/modules/estacionamiento_publico/CargaEdoExPublicos.vue') },
    { path: 'predio-carto', name: 'estacionamiento-publico-predio-carto', component: () => import('@/views/modules/estacionamiento_publico/PredioCartoPublicos.vue') },
    { path: 'reportes-calco', name: 'estacionamiento-publico-reportes-calco', component: () => import('@/views/modules/estacionamiento_publico/ReportesCalcoPublicos.vue') },
    { path: 'solic-rep-folios', name: 'estacionamiento-publico-solic-rep-folios', component: () => import('@/views/modules/estacionamiento_publico/SolicRepFoliosPublicos.vue') },
    { path: 'seguridad-login', name: 'estacionamiento-publico-seguridad-login', component: () => import('@/views/modules/estacionamiento_publico/SeguridadLoginPublicos.vue') },
    { path: 'inspectores', name: 'estacionamiento-publico-inspectores', component: () => import('@/views/modules/estacionamiento_publico/InspectoresPublicos.vue') },
    { path: 'baja-multiple', name: 'estacionamiento-publico-baja-multiple', component: () => import('@/views/modules/estacionamiento_publico/BajaMultiplePublicos.vue') }
  ]
},
// ESTACIONAMIENTO PUBLICO - Acceso (sin layout)
{ path: '/estacionamiento-publico/accesos', name: 'estacionamiento-publico-accesos', component: () => import('@/views/modules/estacionamiento_publico/AccesoPublicos.vue'), meta: { requiresAuth: false } },

// ESTACIONAMIENTO EXCLUSIVO - Rutas con layout (nested routes)
{
  path: '/estacionamiento-exclusivo',
  component: MainLayout,
  children: [
    { path: '', name: 'estacionamiento-exclusivo', component: () => import('@/views/modules/estacionamiento_exclusivo/Menu.vue') },
    { path: 'individual', name: 'estacionamiento-exclusivo-individual', component: () => import('@/views/modules/estacionamiento_exclusivo/Individual.vue') },
    { path: 'individual-folio', name: 'estacionamiento-exclusivo-individual-folio', component: () => import('@/views/modules/estacionamiento_exclusivo/Individual_Folio.vue') },
    { path: 'consulta-reg', name: 'estacionamiento-exclusivo-consulta-reg', component: () => import('@/views/modules/estacionamiento_exclusivo/ConsultaReg.vue') },
    { path: 'cons-his', name: 'estacionamiento-exclusivo-cons-his', component: () => import('@/views/modules/estacionamiento_exclusivo/Cons_his.vue') },
    { path: 'listados', name: 'estacionamiento-exclusivo-listados', component: () => import('@/views/modules/estacionamiento_exclusivo/Listados.vue') },
    { path: 'listados-ade', name: 'estacionamiento-exclusivo-listados-ade', component: () => import('@/views/modules/estacionamiento_exclusivo/Listados_Ade.vue') },
    { path: 'listados-sin-adereq', name: 'estacionamiento-exclusivo-listados-sin-adereq', component: () => import('@/views/modules/estacionamiento_exclusivo/ListadosSinAdereq.vue') },
    { path: 'listx-reg', name: 'estacionamiento-exclusivo-listx-reg', component: () => import('@/views/modules/estacionamiento_exclusivo/ListxReg.vue') },
    { path: 'listx-fec', name: 'estacionamiento-exclusivo-listx-fec', component: () => import('@/views/modules/estacionamiento_exclusivo/ListxFec.vue') },
    { path: 'estdx-folio', name: 'estacionamiento-exclusivo-estdx-folio', component: () => import('@/views/modules/estacionamiento_exclusivo/EstadxFolio.vue') },
    { path: 'modificar', name: 'estacionamiento-exclusivo-modificar', component: () => import('@/views/modules/estacionamiento_exclusivo/Modifcar.vue') },
    { path: 'modificar-bien', name: 'estacionamiento-exclusivo-modificar-bien', component: () => import('@/views/modules/estacionamiento_exclusivo/Modificar_bien.vue') },
    { path: 'modif-masiva', name: 'estacionamiento-exclusivo-modif-masiva', component: () => import('@/views/modules/estacionamiento_exclusivo/Modif_Masiva.vue') },
    { path: 'facturacion', name: 'estacionamiento-exclusivo-facturacion', component: () => import('@/views/modules/estacionamiento_exclusivo/Facturacion.vue') },
    { path: 'requerimientos', name: 'estacionamiento-exclusivo-requerimientos', component: () => import('@/views/modules/estacionamiento_exclusivo/Requerimientos.vue') },
    { path: 'recuperacion', name: 'estacionamiento-exclusivo-recuperacion', component: () => import('@/views/modules/estacionamiento_exclusivo/Recuperacion.vue') },
    { path: 'notificaciones', name: 'estacionamiento-exclusivo-notificaciones', component: () => import('@/views/modules/estacionamiento_exclusivo/Notificaciones.vue') },
    { path: 'notificaciones-mes', name: 'estacionamiento-exclusivo-notificaciones-mes', component: () => import('@/views/modules/estacionamiento_exclusivo/NotificacionesMes.vue') },
    { path: 'prenomina', name: 'estacionamiento-exclusivo-prenomina', component: () => import('@/views/modules/estacionamiento_exclusivo/Prenomina.vue') },
    { path: 'reasignacion', name: 'estacionamiento-exclusivo-reasignacion', component: () => import('@/views/modules/estacionamiento_exclusivo/Reasignacion.vue') },
    { path: 'ejecutores', name: 'estacionamiento-exclusivo-ejecutores', component: () => import('@/views/modules/estacionamiento_exclusivo/Ejecutores.vue') },
    { path: 'abc-ejec', name: 'estacionamiento-exclusivo-abc-ejec', component: () => import('@/views/modules/estacionamiento_exclusivo/ABCEjec.vue') },
    { path: 'lista-ejec', name: 'estacionamiento-exclusivo-lista-ejec', component: () => import('@/views/modules/estacionamiento_exclusivo/Lista_Eje.vue') },
    { path: 'list-eje', name: 'estacionamiento-exclusivo-list-eje', component: () => import('@/views/modules/estacionamiento_exclusivo/List_Eje.vue') },
    { path: 'lista-gastos-cob', name: 'estacionamiento-exclusivo-lista-gastos-cob', component: () => import('@/views/modules/estacionamiento_exclusivo/Lista_GastosCob.vue') },
    { path: 'autoriza-des', name: 'estacionamiento-exclusivo-autoriza-des', component: () => import('@/views/modules/estacionamiento_exclusivo/AutorizaDes.vue') },
    { path: 'carta-invitacion', name: 'estacionamiento-exclusivo-carta-invitacion', component: () => import('@/views/modules/estacionamiento_exclusivo/CartaInvitacion.vue') },
    { path: 'cmult-emision', name: 'estacionamiento-exclusivo-cmult-emision', component: () => import('@/views/modules/estacionamiento_exclusivo/CMultEmision.vue') },
    { path: 'cmult-folio', name: 'estacionamiento-exclusivo-cmult-folio', component: () => import('@/views/modules/estacionamiento_exclusivo/CMultFolio.vue') },
    { path: 'exportar-excel', name: 'estacionamiento-exclusivo-exportar-excel', component: () => import('@/views/modules/estacionamiento_exclusivo/ExportarExcel.vue') },
    { path: 'firma-electronica', name: 'estacionamiento-exclusivo-firma-electronica', component: () => import('@/views/modules/estacionamiento_exclusivo/FirmaElectronica.vue') },
    { path: 'apremios-svn-expedientes', name: 'estacionamiento-exclusivo-apremios-svn-expedientes', component: () => import('@/views/modules/estacionamiento_exclusivo/ApremiosSvnExpedientes.vue') },
    { path: 'apremios-svn-fases', name: 'estacionamiento-exclusivo-apremios-svn-fases', component: () => import('@/views/modules/estacionamiento_exclusivo/ApremiosSvnFases.vue') },
    { path: 'apremios-svn-actuaciones', name: 'estacionamiento-exclusivo-apremios-svn-actuaciones', component: () => import('@/views/modules/estacionamiento_exclusivo/ApremiosSvnActuaciones.vue') },
    { path: 'apremios-svn-notificaciones', name: 'estacionamiento-exclusivo-apremios-svn-notificaciones', component: () => import('@/views/modules/estacionamiento_exclusivo/ApremiosSvnNotificaciones.vue') },
    { path: 'apremios-svn-pagos', name: 'estacionamiento-exclusivo-apremios-svn-pagos', component: () => import('@/views/modules/estacionamiento_exclusivo/ApremiosSvnPagos.vue') },
    { path: 'apremios-svn-reportes', name: 'estacionamiento-exclusivo-apremios-svn-reportes', component: () => import('@/views/modules/estacionamiento_exclusivo/ApremiosSvnReportes.vue') },
    { path: 'sfrm-chgpass', name: 'estacionamiento-exclusivo-sfrm-chgpass', component: () => import('@/views/modules/estacionamiento_exclusivo/sfrm_chgpass.vue') },
    { path: 'rprt-catal-eje', name: 'estacionamiento-exclusivo-rprt-catal-eje', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtCATAL_EJE.vue') },
    { path: 'rprt-estadx-folio', name: 'estacionamiento-exclusivo-rprt-estadx-folio', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtEstadxfolio.vue') },
    { path: 'rprt-list-eje', name: 'estacionamiento-exclusivo-rprt-list-eje', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtList_Eje.vue') },
    { path: 'rprt-listados', name: 'estacionamiento-exclusivo-rprt-listados', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtListados.vue') },
    { path: 'rprt-listax-fec', name: 'estacionamiento-exclusivo-rprt-listax-fec', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtListaxFec.vue') },
    { path: 'rprt-listax-reg-aseo', name: 'estacionamiento-exclusivo-rprt-listax-reg-aseo', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtListaxRegAseo.vue') },
    { path: 'rprt-listax-reg-estacionometro', name: 'estacionamiento-exclusivo-rprt-listax-reg-estacionometro', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtListaxRegEstacionometro.vue') },
    { path: 'rprt-listax-reg-mer', name: 'estacionamiento-exclusivo-rprt-listax-reg-mer', component: () => import('@/views/modules/estacionamiento_exclusivo/RprtListaxRegMer.vue') },
    { path: 'rpt-fact-merc', name: 'estacionamiento-exclusivo-rpt-fact-merc', component: () => import('@/views/modules/estacionamiento_exclusivo/RptFact_Merc.vue') },
    { path: 'rpt-lista-mercados', name: 'estacionamiento-exclusivo-rpt-lista-mercados', component: () => import('@/views/modules/estacionamiento_exclusivo/RptLista_mercados.vue') },
    { path: 'rpt-listado-aseo', name: 'estacionamiento-exclusivo-rpt-listado-aseo', component: () => import('@/views/modules/estacionamiento_exclusivo/RptListado_Aseo.vue') },
    { path: 'rpt-listax-reg-pub', name: 'estacionamiento-exclusivo-rpt-listax-reg-pub', component: () => import('@/views/modules/estacionamiento_exclusivo/RptListaxRegPub.vue') },
    { path: 'rpt-prenomina', name: 'estacionamiento-exclusivo-rpt-prenomina', component: () => import('@/views/modules/estacionamiento_exclusivo/RptPrenomina.vue') },
    { path: 'rpt-recup-aseo', name: 'estacionamiento-exclusivo-rpt-recup-aseo', component: () => import('@/views/modules/estacionamiento_exclusivo/RptRecup_Aseo.vue') },
    { path: 'rpt-recup-merc', name: 'estacionamiento-exclusivo-rpt-recup-merc', component: () => import('@/views/modules/estacionamiento_exclusivo/RptRecup_Merc.vue') },
    { path: 'rpt-req-aseo', name: 'estacionamiento-exclusivo-rpt-req-aseo', component: () => import('@/views/modules/estacionamiento_exclusivo/RptReq_Aseo.vue') },
    { path: 'rpt-req-merc', name: 'estacionamiento-exclusivo-rpt-req-merc', component: () => import('@/views/modules/estacionamiento_exclusivo/RptReq_Merc.vue') },
    { path: 'rpt-req-pba-aseo', name: 'estacionamiento-exclusivo-rpt-req-pba-aseo', component: () => import('@/views/modules/estacionamiento_exclusivo/RptReq_Pba_Aseo.vue') },
    { path: 'rpt-req-pba', name: 'estacionamiento-exclusivo-rpt-req-pba', component: () => import('@/views/modules/estacionamiento_exclusivo/RptReq_pba.vue') },
    { path: 'listados-ade-aseo', name: 'estacionamiento-exclusivo-listados-ade-aseo', component: () => import('@/views/modules/estacionamiento_exclusivo/ListadosAdeAseoForm.vue') },
    { path: 'listados-ade-exclusivos', name: 'estacionamiento-exclusivo-listados-ade-exclusivos', component: () => import('@/views/modules/estacionamiento_exclusivo/ListadosAdeExclusivosForm.vue') },
    { path: 'listados-ade-infracciones', name: 'estacionamiento-exclusivo-listados-ade-infracciones', component: () => import('@/views/modules/estacionamiento_exclusivo/ListadosAdeInfraccionesForm.vue') },
    { path: 'listados-ade-mercados', name: 'estacionamiento-exclusivo-listados-ade-mercados', component: () => import('@/views/modules/estacionamiento_exclusivo/ListadosAdeMercadosForm.vue') },
    { path: 'listados-ade-publicos', name: 'estacionamiento-exclusivo-listados-ade-publicos', component: () => import('@/views/modules/estacionamiento_exclusivo/ListadosAdePublicosForm.vue') },
    { path: 'menu', name: 'estacionamiento-exclusivo-menu', component: () => import('@/views/modules/estacionamiento_exclusivo/Menu.vue') },
    { path: 'report-autor', name: 'estacionamiento-exclusivo-report-autor', component: () => import('@/views/modules/estacionamiento_exclusivo/ReportAutor.vue') },
    { path: 'modulo-db', name: 'estacionamiento-exclusivo-modulo-db', component: () => import('@/views/modules/estacionamiento_exclusivo/ModuloDb.vue') },
    { path: 'unit9', name: 'estacionamiento-exclusivo-unit9', component: () => import('@/views/modules/estacionamiento_exclusivo/UNIT9.vue') },
    { path: 'loader', name: 'estacionamiento-exclusivo-loader', component: () => import('@/views/modules/estacionamiento_exclusivo/Loader.vue') }
  ]
},
// ESTACIONAMIENTO EXCLUSIVO - Acceso (sin layout)
{ path: '/estacionamiento-exclusivo/acceso', name: 'estacionamiento-exclusivo-acceso', component: () => import('@/views/modules/estacionamiento_exclusivo/acceso.vue'), meta: { requiresAuth: false } },
    // MULTAS REGLAMENTOS - Rutas con layout (nested routes)
    {
      path: '/multas-reglamentos',
      component: MainLayout,
      children: [
        { path: '', name: 'multas-reglamentos', component: () => import('@/views/modules/multas_reglamentos/index.vue') },
        { path: 'captura-dif', name: 'multas-reglamentos-captura-dif', component: () => import('@/views/modules/multas_reglamentos/CapturaDif.vue') },
        { path: 'carta-invitacion', name: 'multas-reglamentos-carta-invitacion', component: () => import('@/views/modules/multas_reglamentos/CartaInvitacion.vue') },
        { path: 'drecgo-fosa', name: 'multas-reglamentos-drecgo-fosa', component: () => import('@/views/modules/multas_reglamentos/DrecgoFosa.vue') },
        { path: 'drecgo-trans', name: 'multas-reglamentos-drecgo-trans', component: () => import('@/views/modules/multas_reglamentos/DrecgoTrans.vue') },
        { path: 'ejecutores', name: 'multas-reglamentos-ejecutores', component: () => import('@/views/modules/multas_reglamentos/Ejecutores.vue') },
        { path: 'exclusivos-upd', name: 'multas-reglamentos-exclusivos-upd', component: () => import('@/views/modules/multas_reglamentos/Exclusivos_Upd.vue') },
        { path: 'extractos-rpt', name: 'multas-reglamentos-extractos-rpt', component: () => import('@/views/modules/multas_reglamentos/ExtractosRpt.vue') },
        { path: 'firma-electronica', name: 'multas-reglamentos-firma-electronica', component: () => import('@/views/modules/multas_reglamentos/FirmaElectronica.vue') },
        { path: 'fol-multa', name: 'multas-reglamentos-fol-multa', component: () => import('@/views/modules/multas_reglamentos/FolMulta.vue') },
        { path: 'actualiza-fecha-empresas', name: 'multas-reglamentos-actualiza-fecha-empresas', component: () => import('@/views/modules/multas_reglamentos/ActualizaFechaEmpresas.vue') },
        { path: 'aplica-sdos-favor', name: 'multas-reglamentos-aplica-sdos-favor', component: () => import('@/views/modules/multas_reglamentos/AplicaSdosFavor.vue') },
        { path: 'catastro-dm', name: 'multas-reglamentos-catastro-dm', component: () => import('@/views/modules/multas_reglamentos/CatastroDM.vue') },
        { path: 'consreq400', name: 'multas-reglamentos-consreq400', component: () => import('@/views/modules/multas_reglamentos/ConsReq400.vue') },
        { path: 'reqtrans', name: 'multas-reglamentos-reqtrans', component: () => import('@/views/modules/multas_reglamentos/ReqTrans.vue') },
        { path: 'bloqueo-multa', name: 'multas-reglamentos-bloqueo-multa', component: () => import('@/views/modules/multas_reglamentos/BloqueoMulta.vue') },
        { path: 'desc-derechos-merc', name: 'multas-reglamentos-desc-derechos-merc', component: () => import('@/views/modules/multas_reglamentos/DescDerechosMerc.vue') },
        { path: 'empresas', name: 'multas-reglamentos-empresas', component: () => import('@/views/modules/multas_reglamentos/Empresas.vue') },
        { path: 'gastos-transmision', name: 'multas-reglamentos-gastos-transmision', component: () => import('@/views/modules/multas_reglamentos/GastosTransmision.vue') },
        { path: 'hastafrm', name: 'multas-reglamentos-hastafrm', component: () => import('@/views/modules/multas_reglamentos/Hastafrm.vue') },
        { path: 'imprime-desctos', name: 'multas-reglamentos-imprime-desctos', component: () => import('@/views/modules/multas_reglamentos/ImprimeDesctos.vue') },
        { path: 'list-ana', name: 'multas-reglamentos-list-ana', component: () => import('@/views/modules/multas_reglamentos/ListAna.vue') },
        { path: 'lista-diferencias', name: 'multas-reglamentos-lista-diferencias', component: () => import('@/views/modules/multas_reglamentos/ListaDiferencias.vue') },
        { path: 'listado-multiple', name: 'multas-reglamentos-listado-multiple', component: () => import('@/views/modules/multas_reglamentos/ListadoMultiple.vue') },
        { path: 'modif-masiva', name: 'multas-reglamentos-modif-masiva', component: () => import('@/views/modules/multas_reglamentos/ModifMasiva.vue') },
        { path: 'multas-dm', name: 'multas-reglamentos-multas-dm', component: () => import('@/views/modules/multas_reglamentos/MultasDM.vue') },
        { path: 'otorgadescto', name: 'multas-reglamentos-otorgadescto', component: () => import('@/views/modules/multas_reglamentos/Otorgadescto.vue') },
        { path: 'pagos-espe', name: 'multas-reglamentos-pagos-espe', component: () => import('@/views/modules/multas_reglamentos/PagosEspe.vue') },
        { path: 'periodo-inicial', name: 'multas-reglamentos-periodo-inicial', component: () => import('@/views/modules/multas_reglamentos/PeriodoInicial.vue') },
        { path: 'propuestatab', name: 'multas-reglamentos-propuestatab', component: () => import('@/views/modules/multas_reglamentos/Propuestatab.vue') },
        { path: 'publicos-upd', name: 'multas-reglamentos-publicos-upd', component: () => import('@/views/modules/multas_reglamentos/Publicos_Upd.vue') },
        { path: 'regsecy-mas', name: 'multas-reglamentos-regsecy-mas', component: () => import('@/views/modules/multas_reglamentos/RegSecyMas.vue') },
        { path: 'rep-desc-impto', name: 'multas-reglamentos-rep-desc-impto', component: () => import('@/views/modules/multas_reglamentos/RepDescImpto.vue') },
        { path: 'rep-oper', name: 'multas-reglamentos-rep-oper', component: () => import('@/views/modules/multas_reglamentos/RepOper.vue') },
        { path: 'req', name: 'multas-reglamentos-req', component: () => import('@/views/modules/multas_reglamentos/Req.vue') },
        { path: 'req-frm', name: 'multas-reglamentos-req-frm', component: () => import('@/views/modules/multas_reglamentos/ReqFrm.vue') },
        { path: 'req-promocion', name: 'multas-reglamentos-req-promocion', component: () => import('@/views/modules/multas_reglamentos/ReqPromocion.vue') },
        { path: 'requerimientos-dm', name: 'multas-reglamentos-requerimientos-dm', component: () => import('@/views/modules/multas_reglamentos/RequerimientosDM.vue') },
        { path: 'requerx-cvecat', name: 'multas-reglamentos-requerx-cvecat', component: () => import('@/views/modules/multas_reglamentos/RequerxCvecat.vue') },
        { path: 'resolucion-juez', name: 'multas-reglamentos-resolucion-juez', component: () => import('@/views/modules/multas_reglamentos/ResolucionJuez.vue') },
        { path: 'sdosfavor-dm', name: 'multas-reglamentos-sdosfavor-dm', component: () => import('@/views/modules/multas_reglamentos/SdosFavorDM.vue') },
        { path: 'sdosfavor-ctrlexp', name: 'multas-reglamentos-sdosfavor-ctrlexp', component: () => import('@/views/modules/multas_reglamentos/SdosFavor_CtrlExp.vue') },
        { path: 'sdosfavor-pagos', name: 'multas-reglamentos-sdosfavor-pagos', component: () => import('@/views/modules/multas_reglamentos/SdosFavor_Pagos.vue') },
        { path: 'sinligarfrm', name: 'multas-reglamentos-sinligarfrm', component: () => import('@/views/modules/multas_reglamentos/SinLigarFrm.vue') },
        { path: 'sol-sdos-favor', name: 'multas-reglamentos-sol-sdos-favor', component: () => import('@/views/modules/multas_reglamentos/SolSdosFavor.vue') },
        { path: 'tdm-conection', name: 'multas-reglamentos-tdm-conection', component: () => import('@/views/modules/multas_reglamentos/TDMConection.vue') },
        { path: 'ubicodifica', name: 'multas-reglamentos-ubicodifica', component: () => import('@/views/modules/multas_reglamentos/Ubicodifica.vue') },
        { path: 'autdescto', name: 'multas-reglamentos-autdescto', component: () => import('@/views/modules/multas_reglamentos/autdescto.vue') },
        { path: 'bloqctasreqfrm', name: 'multas-reglamentos-bloqctasreqfrm', component: () => import('@/views/modules/multas_reglamentos/bloqctasreqfrm.vue') },
        { path: 'busque', name: 'multas-reglamentos-busque', component: () => import('@/views/modules/multas_reglamentos/busque.vue') },
        { path: 'canc', name: 'multas-reglamentos-canc', component: () => import('@/views/modules/multas_reglamentos/canc.vue') },
        { path: 'centrosfrm', name: 'multas-reglamentos-centrosfrm', component: () => import('@/views/modules/multas_reglamentos/centrosfrm.vue') },
        { path: 'codificafrm', name: 'multas-reglamentos-codificafrm', component: () => import('@/views/modules/multas_reglamentos/codificafrm.vue') },
        { path: 'conscentrosfrm', name: 'multas-reglamentos-conscentrosfrm', component: () => import('@/views/modules/multas_reglamentos/conscentrosfrm.vue') },
        { path: 'consdesc', name: 'multas-reglamentos-consdesc', component: () => import('@/views/modules/multas_reglamentos/consdesc.vue') },
        { path: ':view', name: 'multas-reglamentos-loader', component: () => import('@/views/modules/multas_reglamentos/Loader.vue') }
      ]
    },
    // MULTAS REGLAMENTOS - Acceso (sin layout)
    { path: '/multas-reglamentos/acceso', name: 'multas-reglamentos-acceso', component: () => import('@/views/modules/multas_reglamentos/Acceso.vue'), meta: { requiresAuth: false } },
    // CEMENTERIOS - Rutas con layout (nested routes)
    {
      path: '/cementerios',
      component: MainLayout,
      children: [
        { path: '', name: 'cementerios', component: () => import('@/views/modules/cementerios/index.vue') },
        { path: 'abcementer', name: 'cementerios-abcementer', component: () => import('@/views/modules/cementerios/ABCementer.vue') },
        { path: 'titulos', name: 'cementerios-titulos', component: () => import('@/views/modules/cementerios/Titulos.vue') },
        { path: 'consultafol', name: 'cementerios-consultafol', component: () => import('@/views/modules/cementerios/ConsultaFol.vue') },
        { path: 'abcpagos', name: 'cementerios-abcpagos', component: () => import('@/views/modules/cementerios/ABCPagos.vue') },
        { path: 'liquidaciones', name: 'cementerios-liquidaciones', component: () => import('@/views/modules/cementerios/Liquidaciones.vue') },
        { path: 'abcfolio', name: 'cementerios-abcfolio', component: () => import('@/views/modules/cementerios/ABCFolio.vue') },
        { path: 'bonificaciones', name: 'cementerios-bonificaciones', component: () => import('@/views/modules/cementerios/Bonificaciones.vue') },
        { path: 'descuentos', name: 'cementerios-descuentos', component: () => import('@/views/modules/cementerios/Descuentos.vue') },
        { path: 'abcrecargos', name: 'cementerios-abcrecargos', component: () => import('@/views/modules/cementerios/ABCRecargos.vue') },
        { path: 'trasladofol', name: 'cementerios-trasladofol', component: () => import('@/views/modules/cementerios/TrasladoFol.vue') },
        { path: 'traslados', name: 'cementerios-traslados', component: () => import('@/views/modules/cementerios/Traslados.vue') },
        { path: 'duplicados', name: 'cementerios-duplicados', component: () => import('@/views/modules/cementerios/Duplicados.vue') },
        { path: 'multiplefecha', name: 'cementerios-multiplefecha', component: () => import('@/views/modules/cementerios/Multiplefecha.vue') },
        { path: 'multiplenombre', name: 'cementerios-multiplenombre', component: () => import('@/views/modules/cementerios/MultipleNombre.vue') },
        { path: 'multiplercm', name: 'cementerios-multiplercm', component: () => import('@/views/modules/cementerios/MultipleRCM.vue') },
        { path: 'conindividual', name: 'cementerios-conindividual', component: () => import('@/views/modules/cementerios/ConIndividual.vue') },
        { path: 'consultaguad', name: 'cementerios-consultaguad', component: () => import('@/views/modules/cementerios/ConsultaGuad.vue') },
        { path: 'consultajardin', name: 'cementerios-consultajardin', component: () => import('@/views/modules/cementerios/ConsultaJardin.vue') },
        { path: 'consultamezq', name: 'cementerios-consultamezq', component: () => import('@/views/modules/cementerios/ConsultaMezq.vue') },
        { path: 'consultasandres', name: 'cementerios-consultasandres', component: () => import('@/views/modules/cementerios/ConsultaSAndres.vue') },
        { path: 'estad-adeudo', name: 'cementerios-estad-adeudo', component: () => import('@/views/modules/cementerios/Estad_adeudo.vue') },
        { path: 'list-mov', name: 'cementerios-list-mov', component: () => import('@/views/modules/cementerios/List_Mov.vue') },
        { path: 'rep-a-cobrar', name: 'cementerios-rep-a-cobrar', component: () => import('@/views/modules/cementerios/Rep_a_Cobrar.vue') },
        { path: 'rep-bon', name: 'cementerios-rep-bon', component: () => import('@/views/modules/cementerios/Rep_Bon.vue') },
        { path: 'abcpagosxfol', name: 'cementerios-abcpagosxfol', component: () => import('@/views/modules/cementerios/ABCPagosxfol.vue') },
        { path: 'consultarcm', name: 'cementerios-consultarcm', component: () => import('@/views/modules/cementerios/ConsultaRCM.vue') },
        { path: 'consulta400', name: 'cementerios-consulta400', component: () => import('@/views/modules/cementerios/Consulta400.vue') },
        { path: 'bonificacion1', name: 'cementerios-bonificacion1', component: () => import('@/views/modules/cementerios/Bonificacion1.vue') },
        { path: 'consultanombre', name: 'cementerios-consultanombre', component: () => import('@/views/modules/cementerios/ConsultaNombre.vue') },
        { path: 'rpttitulos', name: 'cementerios-rpttitulos', component: () => import('@/views/modules/cementerios/RptTitulos.vue') },
        { path: 'titulossin', name: 'cementerios-titulossin', component: () => import('@/views/modules/cementerios/TitulosSin.vue') },
        { path: 'trasladofolsin', name: 'cementerios-trasladofolsin', component: () => import('@/views/modules/cementerios/TrasladoFolSin.vue') },
        { path: 'menu', name: 'cementerios-menu', component: () => import('@/views/modules/cementerios/Menu.vue') },
        { path: 'modulo', name: 'cementerios-modulo', component: () => import('@/views/modules/cementerios/Modulo.vue') },
        { path: 'chgpass', name: 'cementerios-chgpass', component: () => import('@/views/modules/cementerios/sfrm_chgpass.vue') }
      ]
    },
    // CEMENTERIOS - Acceso (sin layout)
    { path: '/cementerios/acceso', name: 'cementerios-acceso', component: () => import('@/views/modules/cementerios/Acceso.vue'), meta: { requiresAuth: false } },
    {
      path: '/cementerio',
      name: 'cementerio',
      component: () => import('@/views/modules/cementerios/index.vue')
    },
    // MERCADOS - Rutas con layout (nested routes)
    {
      path: '/mercados',
      component: MainLayout,
      children: [
        { path: '', name: 'mercados', component: () => import('@/views/modules/mercados/index.vue') },
        { path: 'padron-locales', name: 'mercados-padron-locales', component: () => import('@/views/modules/mercados/PadronLocales.vue') },
        { path: 'locales-mtto', name: 'mercados-locales-mtto', component: () => import('@/views/modules/mercados/LocalesMtto.vue') },
        { path: 'adeudos-locales', name: 'mercados-adeudos-locales', component: () => import('@/views/modules/mercados/AdeudosLocales.vue') },
        { path: 'alta-pagos', name: 'mercados-alta-pagos', component: () => import('@/views/modules/mercados/AltaPagos.vue') },
        { path: 'emision-locales', name: 'mercados-emision-locales', component: () => import('@/views/modules/mercados/EmisionLocales.vue') },
        { path: 'estad-pagos-adeudos', name: 'mercados-estad-pagos-adeudos', component: () => import('@/views/modules/mercados/EstadPagosyAdeudos.vue') },
        { path: 'carga-pag-locales', name: 'mercados-carga-pag-locales', component: () => import('@/views/modules/mercados/CargaPagLocales.vue') },
        { path: 'listados-locales', name: 'mercados-listados-locales', component: () => import('@/views/modules/mercados/ListadosLocales.vue') },
        { path: 'rpt-pagos-locales', name: 'mercados-rpt-pagos-locales', component: () => import('@/views/modules/mercados/RptPagosLocales.vue') },
        { path: 'padron-energia', name: 'mercados-padron-energia', component: () => import('@/views/modules/mercados/PadronEnergia.vue') },
        { path: 'energia-mtto', name: 'mercados-energia-mtto', component: () => import('@/views/modules/mercados/EnergiaMtto.vue') },
        { path: 'adeudos-energia', name: 'mercados-adeudos-energia', component: () => import('@/views/modules/mercados/AdeudosEnergia.vue') },
        { path: 'catalogo-mercados', name: 'mercados-catalogo-mercados', component: () => import('@/views/modules/mercados/CatalogoMercados.vue') },
        { path: 'consulta-datos-locales', name: 'mercados-consulta-datos-locales', component: () => import('@/views/modules/mercados/ConsultaDatosLocales.vue') },
        { path: 'consulta-datos-energia', name: 'mercados-consulta-datos-energia', component: () => import('@/views/modules/mercados/ConsultaDatosEnergia.vue') },
        { path: 'cuotas-mdo', name: 'mercados-cuotas-mdo', component: () => import('@/views/modules/mercados/CuotasMdo.vue') },
        { path: 'categoria', name: 'mercados-categoria', component: () => import('@/views/modules/mercados/Categoria.vue') },
        { path: 'giros', name: 'mercados-giros', component: () => import('@/views/modules/mercados/Giros.vue') },
        { path: 'secciones', name: 'mercados-secciones', component: () => import('@/views/modules/mercados/Secciones.vue') },
        { path: 'recaudadoras-mercados', name: 'mercados-recaudadoras-mercados', component: () => import('@/views/modules/mercados/RecaudadorasMercados.vue') },
        { path: 'zonas-mercados', name: 'mercados-zonas-mercados', component: () => import('@/views/modules/mercados/ZonasMercados.vue') },
        { path: 'reporte-general-mercados', name: 'mercados-reporte-general-mercados', component: () => import('@/views/modules/mercados/ReporteGeneralMercados.vue') },
        { path: 'padron-global', name: 'mercados-padron-global', component: () => import('@/views/modules/mercados/PadronGlobal.vue') },
        { path: 'alta-pagos-energia', name: 'mercados-alta-pagos-energia', component: () => import('@/views/modules/mercados/AltaPagosEnergia.vue') },
        { path: 'cons-pagos', name: 'mercados-cons-pagos', component: () => import('@/views/modules/mercados/ConsPagos.vue') },
        { path: 'pagos-individual', name: 'mercados-pagos-individual', component: () => import('@/views/modules/mercados/PagosIndividual.vue') },
        { path: 'cuotas-energia', name: 'mercados-cuotas-energia', component: () => import('@/views/modules/mercados/CuotasEnergia.vue') },
        { path: 'emision-energia', name: 'mercados-emision-energia', component: () => import('@/views/modules/mercados/EmisionEnergia.vue') },
        { path: 'cuotas-energia-mntto', name: 'mercados-cuotas-energia-mntto', component: () => import('@/views/modules/mercados/CuotasEnergiaMntto.vue') },
        { path: 'datos-convenio', name: 'mercados-datos-convenio', component: () => import('@/views/modules/mercados/DatosConvenio.vue') },
        { path: 'datos-individuales', name: 'mercados-datos-individuales', component: () => import('@/views/modules/mercados/DatosIndividuales.vue') },
        { path: 'estadisticas', name: 'mercados-estadisticas', component: () => import('@/views/modules/mercados/Estadisticas.vue') },
        { path: 'catalogo-mntto', name: 'mercados-catalogo-mntto', component: () => import('@/views/modules/mercados/CatalogoMntto.vue') },
        { path: 'cons-requerimientos', name: 'mercados-cons-requerimientos', component: () => import('@/views/modules/mercados/ConsRequerimientos.vue') },
        { path: 'condonacion', name: 'mercados-condonacion', component: () => import('@/views/modules/mercados/Condonacion.vue') },
        { path: 'ade-global-locales', name: 'mercados-ade-global-locales', component: () => import('@/views/modules/mercados/AdeGlobalLocales.vue') },
        { path: 'ade-energia-grl', name: 'mercados-ade-energia-grl', component: () => import('@/views/modules/mercados/AdeEnergiaGrl.vue') },
        { path: 'adeudos-loc-grl', name: 'mercados-adeudos-loc-grl', component: () => import('@/views/modules/mercados/AdeudosLocGrl.vue') },
        { path: 'aut-carga-pagos', name: 'mercados-aut-carga-pagos', component: () => import('@/views/modules/mercados/AutCargaPagos.vue') },
        { path: 'aut-carga-pagos-mtto', name: 'mercados-aut-carga-pagos-mtto', component: () => import('@/views/modules/mercados/AutCargaPagosMtto.vue') },
        { path: 'carga-diversos-esp', name: 'mercados-carga-diversos-esp', component: () => import('@/views/modules/mercados/CargaDiversosEsp.vue') },
        { path: 'carga-pag-energia', name: 'mercados-carga-pag-energia', component: () => import('@/views/modules/mercados/CargaPagEnergia.vue') },
        { path: 'carga-pag-energia-elec', name: 'mercados-carga-pag-energia-elec', component: () => import('@/views/modules/mercados/CargaPagEnergiaElec.vue') },
        { path: 'carga-pag-especial', name: 'mercados-carga-pag-especial', component: () => import('@/views/modules/mercados/CargaPagEspecial.vue') },
        { path: 'carga-pag-mercado', name: 'mercados-carga-pag-mercado', component: () => import('@/views/modules/mercados/CargaPagMercado.vue') },
        { path: 'carga-pagos-texto', name: 'mercados-carga-pagos-texto', component: () => import('@/views/modules/mercados/CargaPagosTexto.vue') },
        { path: 'categoria-mntto', name: 'mercados-categoria-mntto', component: () => import('@/views/modules/mercados/CategoriaMntto.vue') },
        { path: 'cons-captura-energia', name: 'mercados-cons-captura-energia', component: () => import('@/views/modules/mercados/ConsCapturaEnergia.vue') },
        { path: 'cons-captura-fecha', name: 'mercados-cons-captura-fecha', component: () => import('@/views/modules/mercados/ConsCapturaFecha.vue') },
        { path: 'cons-captura-fecha-energia', name: 'mercados-cons-captura-fecha-energia', component: () => import('@/views/modules/mercados/ConsCapturaFechaEnergia.vue') },
        { path: 'cons-captura-merc', name: 'mercados-cons-captura-merc', component: () => import('@/views/modules/mercados/ConsCapturaMerc.vue') },
        { path: 'cons-pagos-energia', name: 'mercados-cons-pagos-energia', component: () => import('@/views/modules/mercados/ConsPagosEnergia.vue') },
        { path: 'cons-pagos-locales', name: 'mercados-cons-pagos-locales', component: () => import('@/views/modules/mercados/ConsPagosLocales.vue') },
        { path: 'consulta-general', name: 'mercados-consulta-general', component: () => import('@/views/modules/mercados/ConsultaGeneral.vue') },
        { path: 'cons-condonacion', name: 'mercados-cons-condonacion', component: () => import('@/views/modules/mercados/ConsCondonacion.vue') },
        { path: 'cons-condonacion-energia', name: 'mercados-cons-condonacion-energia', component: () => import('@/views/modules/mercados/ConsCondonacionEnergia.vue') },
        { path: 'cuotas-mdo-mntto', name: 'mercados-cuotas-mdo-mntto', component: () => import('@/views/modules/mercados/CuotasMdoMntto.vue') },
        { path: 'cve-cuota', name: 'mercados-cve-cuota', component: () => import('@/views/modules/mercados/CveCuota.vue') },
        { path: 'cve-diferencias', name: 'mercados-cve-diferencias', component: () => import('@/views/modules/mercados/CveDiferencias.vue') },
        { path: 'fecha-descuento', name: 'mercados-fecha-descuento', component: () => import('@/views/modules/mercados/FechaDescuento.vue') },
        { path: 'fechas-descuento-mntto', name: 'mercados-fechas-descuento-mntto', component: () => import('@/views/modules/mercados/FechasDescuentoMntto.vue') },
        { path: 'recargos', name: 'mercados-recargos', component: () => import('@/views/modules/mercados/Recargos.vue') },
        { path: 'datos-movimientos', name: 'mercados-datos-movimientos', component: () => import('@/views/modules/mercados/DatosMovimientos.vue') },
        { path: 'datos-requerimientos', name: 'mercados-datos-requerimientos', component: () => import('@/views/modules/mercados/DatosRequerimientos.vue') },
        { path: 'locales-modif', name: 'mercados-locales-modif', component: () => import('@/views/modules/mercados/LocalesModif.vue') },
        { path: 'energia-modif', name: 'mercados-energia-modif', component: () => import('@/views/modules/mercados/EnergiaModif.vue') },
        { path: 'emision-libertad', name: 'mercados-emision-libertad', component: () => import('@/views/modules/mercados/EmisionLibertad.vue') },
        { path: 'pagos-ene-cons', name: 'mercados-pagos-ene-cons', component: () => import('@/views/modules/mercados/PagosEneCons.vue') },
        { path: 'pagos-loc-grl', name: 'mercados-pagos-loc-grl', component: () => import('@/views/modules/mercados/PagosLocGrl.vue') },
        { path: 'prescripcion', name: 'mercados-prescripcion', component: () => import('@/views/modules/mercados/Prescripcion.vue') },
        { path: 'rep-adeud-cond', name: 'mercados-rep-adeud-cond', component: () => import('@/views/modules/mercados/RepAdeudCond.vue') },
        { path: 'rpt-ade-energia-grl', name: 'mercados-rpt-ade-energia-grl', component: () => import('@/views/modules/mercados/RptAdeEnergiaGrl.vue') },
        { path: 'rpt-adeudos-locales', name: 'mercados-rpt-adeudos-locales', component: () => import('@/views/modules/mercados/RptAdeudosLocales.vue') },
        { path: 'rpt-adeudos-energia', name: 'mercados-rpt-adeudos-energia', component: () => import('@/views/modules/mercados/RptAdeudosEnergia.vue') },
        { path: 'rpt-adeudos-anteriores', name: 'mercados-rpt-adeudos-anteriores', component: () => import('@/views/modules/mercados/RptAdeudosAnteriores.vue') },
        { path: 'rpt-adeudos-abastos1998', name: 'mercados-rpt-adeudos-abastos1998', component: () => import('@/views/modules/mercados/RptAdeudosAbastos1998.vue') },
        { path: 'rpt-desgloce-ade-porimporte', name: 'mercados-rpt-desgloce-ade-porimporte', component: () => import('@/views/modules/mercados/RptDesgloceAdeporImporte.vue') },
        { path: 'rpt-emision-locales', name: 'mercados-rpt-emision-locales', component: () => import('@/views/modules/mercados/RptEmisionLocales.vue') },
        { path: 'rpt-emision-rbos-abastos', name: 'mercados-rpt-emision-rbos-abastos', component: () => import('@/views/modules/mercados/RptEmisionRbosAbastos.vue') },
        { path: 'rpt-emision-laser', name: 'mercados-rpt-emision-laser', component: () => import('@/views/modules/mercados/RptEmisionLaser.vue') },
        { path: 'rpt-emision-energia', name: 'mercados-rpt-emision-energia', component: () => import('@/views/modules/mercados/RptEmisionEnergia.vue') },
        { path: 'rpt-factura-emision', name: 'mercados-rpt-factura-emision', component: () => import('@/views/modules/mercados/RptFacturaEmision.vue') },
        { path: 'rpt-factura-energia', name: 'mercados-rpt-factura-energia', component: () => import('@/views/modules/mercados/RptFacturaEnergia.vue') },
        { path: 'rpt-factura-glunes', name: 'mercados-rpt-factura-glunes', component: () => import('@/views/modules/mercados/RptFacturaGLunes.vue') },
        { path: 'rpt-padron-locales', name: 'mercados-rpt-padron-locales', component: () => import('@/views/modules/mercados/RptPadronLocales.vue') },
        { path: 'rpt-padron-energia', name: 'mercados-rpt-padron-energia', component: () => import('@/views/modules/mercados/RptPadronEnergia.vue') },
        { path: 'rpt-locales-giro', name: 'mercados-rpt-locales-giro', component: () => import('@/views/modules/mercados/RptLocalesGiro.vue') },
        { path: 'rpt-mercados', name: 'mercados-rpt-mercados', component: () => import('@/views/modules/mercados/RptMercados.vue') },
        { path: 'rpt-zonificacion', name: 'mercados-rpt-zonificacion', component: () => import('@/views/modules/mercados/RptZonificacion.vue') },
        { path: 'rpt-movimientos', name: 'mercados-rpt-movimientos', component: () => import('@/views/modules/mercados/RptMovimientos.vue') },
        { path: 'ingreso-captura', name: 'mercados-ingreso-captura', component: () => import('@/views/modules/mercados/IngresoCaptura.vue') },
        { path: 'ingreso-lib', name: 'mercados-ingreso-lib', component: () => import('@/views/modules/mercados/IngresoLib.vue') },
        { path: 'rpt-ingreso-zonificado', name: 'mercados-rpt-ingreso-zonificado', component: () => import('@/views/modules/mercados/RptIngresoZonificado.vue') },
        { path: 'rpt-ingresos', name: 'mercados-rpt-ingresos', component: () => import('@/views/modules/mercados/RptIngresos.vue') },
        { path: 'rpt-ingresos-energia', name: 'mercados-rpt-ingresos-energia', component: () => import('@/views/modules/mercados/RptIngresosEnergia.vue') },
        { path: 'rpt-pagos-ano', name: 'mercados-rpt-pagos-ano', component: () => import('@/views/modules/mercados/RptPagosAno.vue') },
        { path: 'rpt-pagos-caja', name: 'mercados-rpt-pagos-caja', component: () => import('@/views/modules/mercados/RptPagosCaja.vue') },
        { path: 'rpt-pagos-detalle', name: 'mercados-rpt-pagos-detalle', component: () => import('@/views/modules/mercados/RptPagosDetalle.vue') },
        { path: 'rpt-pagos-grl', name: 'mercados-rpt-pagos-grl', component: () => import('@/views/modules/mercados/RptPagosGrl.vue') },
        { path: 'rpt-estad-pagos-y-adeudos', name: 'mercados-rpt-estad-pagos-y-adeudos', component: () => import('@/views/modules/mercados/RptEstadPagosyAdeudos.vue') },
        { path: 'rpt-estadistica-adeudos', name: 'mercados-rpt-estadistica-adeudos', component: () => import('@/views/modules/mercados/RptEstadisticaAdeudos.vue') },
        { path: 'cuenta-publica', name: 'mercados-cuenta-publica', component: () => import('@/views/modules/mercados/CuentaPublica.vue') },
        { path: 'rpt-cuenta-publica', name: 'mercados-rpt-cuenta-publica', component: () => import('@/views/modules/mercados/RptCuentaPublica.vue') },
        { path: 'pagos-dif-ingresos', name: 'mercados-pagos-dif-ingresos', component: () => import('@/views/modules/mercados/PagosDifIngresos.vue') },
        { path: 'rpt-resumen-pagos', name: 'mercados-rpt-resumen-pagos', component: () => import('@/views/modules/mercados/RptResumenPagos.vue') },
        { path: 'rpt-saldos-locales', name: 'mercados-rpt-saldos-locales', component: () => import('@/views/modules/mercados/RptSaldosLocales.vue') },
        { path: 'rpt-fechas-vencimiento', name: 'mercados-rpt-fechas-vencimiento', component: () => import('@/views/modules/mercados/RptFechasVencimiento.vue') },
        { path: 'rpt-catalogo-merc', name: 'mercados-rpt-catalogo-merc', component: () => import('@/views/modules/mercados/RptCatalogoMerc.vue') },
        { path: 'paso-adeudos', name: 'mercados-paso-adeudos', component: () => import('@/views/modules/mercados/PasoAdeudos.vue') },
        { path: 'paso-ene', name: 'mercados-paso-ene', component: () => import('@/views/modules/mercados/PasoEne.vue') },
        { path: 'paso-mdos', name: 'mercados-paso-mdos', component: () => import('@/views/modules/mercados/PasoMdos.vue') },
        { path: 'menu', name: 'mercados-menu', component: () => import('@/views/modules/mercados/Menu.vue') }
      ]
    },
    // MERCADOS - Acceso (sin layout)
    { path: '/mercados/acceso', name: 'mercados-acceso', component: () => import('@/views/modules/mercados/Acceso.vue'), meta: { requiresAuth: false } },

    // OTRAS OBLIGACIONES - Rutas con layout (nested routes)
    {
      path: '/otras-obligaciones',
      component: MainLayout,
      children: [
        { path: '', name: 'otras-obligaciones', component: () => import('@/views/modules/otras_obligaciones/index.vue') },
        { path: 'menu', name: 'otras-obligaciones-menu', component: () => import('@/views/modules/otras_obligaciones/Menu.vue') },
        { path: 'gnuevos', name: 'otras-obligaciones-gnuevos', component: () => import('@/views/modules/otras_obligaciones/GNuevos.vue') },
        { path: 'gconsulta', name: 'otras-obligaciones-gconsulta', component: () => import('@/views/modules/otras_obligaciones/GConsulta.vue') },
        { path: 'gconsulta2', name: 'otras-obligaciones-gconsulta2', component: () => import('@/views/modules/otras_obligaciones/GConsulta2.vue') },
        { path: 'gactualiza', name: 'otras-obligaciones-gactualiza', component: () => import('@/views/modules/otras_obligaciones/GActualiza.vue') },
        { path: 'gbaja', name: 'otras-obligaciones-gbaja', component: () => import('@/views/modules/otras_obligaciones/GBaja.vue') },
        { path: 'gadeudos', name: 'otras-obligaciones-gadeudos', component: () => import('@/views/modules/otras_obligaciones/GAdeudos.vue') },
        { path: 'gadeudos-gral', name: 'otras-obligaciones-gadeudos-gral', component: () => import('@/views/modules/otras_obligaciones/GAdeudosGral.vue') },
        { path: 'gadeudos-opc-mult', name: 'otras-obligaciones-gadeudos-opc-mult', component: () => import('@/views/modules/otras_obligaciones/GAdeudos_OpcMult.vue') },
        { path: 'gadeudos-opc-mult-ra', name: 'otras-obligaciones-gadeudos-opc-mult-ra', component: () => import('@/views/modules/otras_obligaciones/GAdeudos_OpcMult_RA.vue') },
        { path: 'gfacturacion', name: 'otras-obligaciones-gfacturacion', component: () => import('@/views/modules/otras_obligaciones/GFacturacion.vue') },
        { path: 'grep-padron', name: 'otras-obligaciones-grep-padron', component: () => import('@/views/modules/otras_obligaciones/GRep_Padron.vue') },
        { path: 'rnuevos', name: 'otras-obligaciones-rnuevos', component: () => import('@/views/modules/otras_obligaciones/RNuevos.vue') },
        { path: 'rconsulta', name: 'otras-obligaciones-rconsulta', component: () => import('@/views/modules/otras_obligaciones/RConsulta.vue') },
        { path: 'ractualiza', name: 'otras-obligaciones-ractualiza', component: () => import('@/views/modules/otras_obligaciones/RActualiza.vue') },
        { path: 'rbaja', name: 'otras-obligaciones-rbaja', component: () => import('@/views/modules/otras_obligaciones/RBaja.vue') },
        { path: 'radeudos', name: 'otras-obligaciones-radeudos', component: () => import('@/views/modules/otras_obligaciones/RAdeudos.vue') },
        { path: 'radeudos-opc-mult', name: 'otras-obligaciones-radeudos-opc-mult', component: () => import('@/views/modules/otras_obligaciones/RAdeudos_OpcMult.vue') },
        { path: 'rfacturacion', name: 'otras-obligaciones-rfacturacion', component: () => import('@/views/modules/otras_obligaciones/RFacturacion.vue') },
        { path: 'rpagados', name: 'otras-obligaciones-rpagados', component: () => import('@/views/modules/otras_obligaciones/RPagados.vue') },
        { path: 'rrep-padron', name: 'otras-obligaciones-rrep-padron', component: () => import('@/views/modules/otras_obligaciones/RRep_Padron.vue') },
        { path: 'rubros', name: 'otras-obligaciones-rubros', component: () => import('@/views/modules/otras_obligaciones/Rubros.vue') },
        { path: 'etiquetas', name: 'otras-obligaciones-etiquetas', component: () => import('@/views/modules/otras_obligaciones/Etiquetas.vue') },
        { path: 'aux-rep', name: 'otras-obligaciones-aux-rep', component: () => import('@/views/modules/otras_obligaciones/AuxRep.vue') },
        { path: 'carga-cartera', name: 'otras-obligaciones-carga-cartera', component: () => import('@/views/modules/otras_obligaciones/CargaCartera.vue') },
        { path: 'carga-valores', name: 'otras-obligaciones-carga-valores', component: () => import('@/views/modules/otras_obligaciones/CargaValores.vue') },
        { path: 'apremios', name: 'otras-obligaciones-apremios', component: () => import('@/views/modules/otras_obligaciones/Apremios.vue') }
      ]
    },
    // OTRAS OBLIGACIONES - Acceso (sin layout)
    { path: '/otras-obligaciones/acceso', name: 'otras-obligaciones-acceso', component: () => import('@/views/modules/otras_obligaciones/Acceso.vue'), meta: { requiresAuth: false } },
    // PADRON LICENCIAS - Rutas con layout (nested routes)
    {
      path: '/padron-licencias',
      component: MainLayout,
      children: [
        { path: '', name: 'padron-licencias', component: () => import('@/views/modules/padron_licencias/index.vue') },
        { path: 'consulta-usuarios', name: 'consulta-usuarios', component: () => import('@/views/modules/padron_licencias/consultausuariosfrm.vue') },
        { path: 'consulta-licencias', name: 'consulta-licencias', component: () => import('@/views/modules/padron_licencias/consultaLicenciafrm.vue') },
        { path: 'consulta-anuncios', name: 'consulta-anuncios', component: () => import('@/views/modules/padron_licencias/consultaAnunciofrm.vue') },
        { path: 'modificacion-licencias', name: 'modificacion-licencias', component: () => import('@/views/modules/padron_licencias/modlicfrm.vue') },
        { path: 'detalle-licencia', name: 'detalle-licencia', component: () => import('@/views/modules/padron_licencias/DetalleLicencia.vue') },
        { path: 'detalle-anuncio', name: 'detalle-anuncio', component: () => import('@/views/modules/padron_licencias/DetalleAnuncio.vue') },
        { path: 'modificacion-tramites/:id?', name: 'modificacion-tramites', component: () => import('@/views/modules/padron_licencias/modtramitefrm.vue') },
        { path: 'consulta-tramites', name: 'consulta-tramites', component: () => import('@/views/modules/padron_licencias/ConsultaTramitefrm.vue') },
        { path: 'solicitud-numero-oficial', name: 'solicitud-numero-oficial', component: () => import('@/views/modules/padron_licencias/constanciaNoOficialfrm.vue') },
        { path: 'constancias', name: 'constancias', component: () => import('@/views/modules/padron_licencias/constanciafrm.vue') },
        { path: 'dictamenes', name: 'dictamenes', component: () => import('@/views/modules/padron_licencias/dictamenfrm.vue') },
        { path: 'baja-licencia', name: 'baja-licencia', component: () => import('@/views/modules/padron_licencias/bajaLicenciafrm.vue') },
        { path: 'cancelacion-tramites', name: 'cancelacion-tramites', component: () => import('@/views/modules/padron_licencias/cancelaTramitefrm.vue') },
        { path: 'bloqueo-domicilios', name: 'bloqueo-domicilios', component: () => import('@/views/modules/padron_licencias/bloqueoDomiciliosfrm.vue') },
        { path: 'bloqueo-rfc', name: 'bloqueo-rfc', component: () => import('@/views/modules/padron_licencias/bloqueoRFCfrm.vue') },
        { path: 'catalogo-giros', name: 'catalogo-giros', component: () => import('@/views/modules/padron_licencias/catalogogirosfrm.vue') },
        { path: 'busqueda-giros', name: 'busqueda-giros', component: () => import('@/views/modules/padron_licencias/buscagirofrm.vue') },
        { path: 'catalogo-actividades', name: 'catalogo-actividades', component: () => import('@/views/modules/padron_licencias/CatalogoActividadesFrm.vue') },
        { path: 'catalogo-requisitos', name: 'catalogo-requisitos', component: () => import('@/views/modules/padron_licencias/CatRequisitos.vue') },
        { path: 'grupos-licencias', name: 'grupos-licencias', component: () => import('@/views/modules/padron_licencias/gruposLicenciasfrm.vue') },
        { path: 'cruces-calles', name: 'cruces-calles', component: () => import('@/views/modules/padron_licencias/Cruces.vue') },
        { path: 'grupos-licencias-abc', name: 'grupos-licencias-abc', component: () => import('@/views/modules/padron_licencias/GruposLicenciasAbcfrm.vue') },
        { path: 'zona-anuncio', name: 'zona-anuncio', component: () => import('@/views/modules/padron_licencias/ZonaAnuncio.vue') },
        { path: 'busqueda-actividad', name: 'busqueda-actividad', component: () => import('@/views/modules/padron_licencias/BusquedaActividadFrm.vue') },
        { path: 'busqueda-scian', name: 'busqueda-scian', component: () => import('@/views/modules/padron_licencias/BusquedaScianFrm.vue') },
        { path: 'busqueda-general', name: 'busqueda-general', component: () => import('@/views/modules/padron_licencias/busque.vue') },
        { path: 'bloquear-licencia', name: 'bloquear-licencia', component: () => import('@/views/modules/padron_licencias/BloquearLicenciafrm.vue') },
        { path: 'bloquear-tramite', name: 'bloquear-tramite', component: () => import('@/views/modules/padron_licencias/BloquearTramitefrm.vue') },
        { path: 'bloquear-anuncio', name: 'bloquear-anuncio', component: () => import('@/views/modules/padron_licencias/BloquearAnunciorm.vue') },
        { path: 'baja-anuncio', name: 'baja-anuncio', component: () => import('@/views/modules/padron_licencias/bajaAnunciofrm.vue') },
        { path: 'reactivar-tramite', name: 'reactivar-tramite', component: () => import('@/views/modules/padron_licencias/ReactivaTramite.vue') },
        { path: 'certificaciones', name: 'certificaciones', component: () => import('@/views/modules/padron_licencias/certificacionesfrm.vue') },
        { path: 'agenda-visitas', name: 'agenda-visitas', component: () => import('@/views/modules/padron_licencias/Agendavisitasfrm.vue') },
        { path: 'registro-solicitud', name: 'registro-solicitud', component: () => import('@/views/modules/padron_licencias/RegistroSolicitud.vue') },
        { path: 'dictamen-uso-suelo', name: 'dictamen-uso-suelo', component: () => import('@/views/modules/padron_licencias/dictamenusodesuelo.vue') },
        { path: 'formatos-ecologia', name: 'formatos-ecologia', component: () => import('@/views/modules/padron_licencias/formatosEcologiafrm.vue') },
        { path: 'documentos', name: 'documentos', component: () => import('@/views/modules/padron_licencias/doctosfrm.vue') },
        { path: 'fecha-seguimiento', name: 'fecha-seguimiento', component: () => import('@/views/modules/padron_licencias/fechasegfrm.vue') },
        { path: 'firma-usuario', name: 'firma-usuario', component: () => import('@/views/modules/padron_licencias/firmausuario.vue') },
        { path: 'liga-anuncio', name: 'liga-anuncio', component: () => import('@/views/modules/padron_licencias/ligaAnunciofrm.vue') },
        { path: 'liga-requisitos', name: 'liga-requisitos', component: () => import('@/views/modules/padron_licencias/LigaRequisitos.vue') },
        { path: 'modific-adeudo', name: 'modific-adeudo', component: () => import('@/views/modules/padron_licencias/modlicAdeudofrm.vue') },
        { path: 'prepago', name: 'prepago', component: () => import('@/views/modules/padron_licencias/prepagofrm.vue') },
        { path: 'propietarios-hologramas', name: 'propietarios-hologramas', component: () => import('@/views/modules/padron_licencias/prophologramasfrm.vue') },
        { path: 'responsivas', name: 'responsivas', component: () => import('@/views/modules/padron_licencias/Responsivafrm.vue') },
        { path: 'hasta', name: 'hasta', component: () => import('@/views/modules/padron_licencias/Hastafrm.vue') },
        { path: 'cartografia-catastral', name: 'cartografia-catastral', component: () => import('@/views/modules/padron_licencias/cartonva.vue') },
        { path: 'carga-predios', name: 'carga-predios', component: () => import('@/views/modules/padron_licencias/carga.vue') },
        { path: 'imp-licencia-reglamentada', name: 'imp-licencia-reglamentada', component: () => import('@/views/modules/padron_licencias/ImpLicenciaReglamentadaFrm.vue') },
        { path: 'imp-oficio', name: 'imp-oficio', component: () => import('@/views/modules/padron_licencias/ImpOficiofrm.vue') },
        { path: 'imp-recibo', name: 'imp-recibo', component: () => import('@/views/modules/padron_licencias/ImpRecibofrm.vue') },
        { path: 'reporte-documentos', name: 'reporte-documentos', component: () => import('@/views/modules/padron_licencias/repdoc.vue') },
        { path: 'reporte-estadisticos', name: 'reporte-estadisticos', component: () => import('@/views/modules/padron_licencias/repEstadisticosLicfrm.vue') },
        { path: 'reporte-estado', name: 'reporte-estado', component: () => import('@/views/modules/padron_licencias/repestado.vue') },
        { path: 'reporte-suspendidas', name: 'reporte-suspendidas', component: () => import('@/views/modules/padron_licencias/repsuspendidasfrm.vue') },
        { path: 'reporte-anuncios-excel', name: 'reporte-anuncios-excel', component: () => import('@/views/modules/padron_licencias/ReporteAnunExcelfrm.vue') },
        { path: 'catastro-dm', name: 'catastro-dm', component: () => import('@/views/modules/padron_licencias/CatastroDM.vue') },
        { path: 'propuesta-tabulador', name: 'propuesta-tabulador', component: () => import('@/views/modules/padron_licencias/Propuestatab.vue') },
        { path: 'empresas', name: 'empresas', component: () => import('@/views/modules/padron_licencias/empresasfrm.vue') },
        { path: 'carga-datos', name: 'carga-datos', component: () => import('@/views/modules/padron_licencias/cargadatosfrm.vue') },
        { path: 'semaforo', name: 'semaforo', component: () => import('@/views/modules/padron_licencias/Semaforo.vue') },
        { path: 'formabuscalle', name: 'formabuscalle', component: () => import('@/views/modules/padron_licencias/formabuscalle.vue') },
        { path: 'formabuscolonia', name: 'formabuscolonia', component: () => import('@/views/modules/padron_licencias/formabuscolonia.vue') },
        { path: 'frmselcalle', name: 'frmselcalle', component: () => import('@/views/modules/padron_licencias/frmselcalle.vue') },
        { path: 'sfrm-chgfirma', name: 'sfrm-chgfirma', component: () => import('@/views/modules/padron_licencias/sfrm_chgfirma.vue') },
        { path: 'tipobloqueo', name: 'tipobloqueo', component: () => import('@/views/modules/padron_licencias/tipobloqueofrm.vue') },
        { path: 'tramite-baja-anuncio', name: 'tramite-baja-anuncio', component: () => import('@/views/modules/padron_licencias/TramiteBajaAnun.vue') },
        { path: 'tramite-baja-licencia', name: 'tramite-baja-licencia', component: () => import('@/views/modules/padron_licencias/TramiteBajaLic.vue') },
        { path: 'observaciones', name: 'observaciones', component: () => import('@/views/modules/padron_licencias/observacionfrm.vue') },
        { path: 'licencias-vigentes', name: 'licencias-vigentes', component: () => import('@/views/modules/padron_licencias/LicenciasVigentesfrm.vue') },
        { path: 'sfrm-chgpass', name: 'sfrm-chgpass', component: () => import('@/views/modules/padron_licencias/sfrm_chgpass.vue') },
        { path: 'grupos-anuncios', name: 'grupos-anuncios', component: () => import('@/views/modules/padron_licencias/gruposAnunciosfrm.vue') },
        { path: 'grupos-anuncios-abc', name: 'grupos-anuncios-abc', component: () => import('@/views/modules/padron_licencias/GruposAnunciosAbcfrm.vue') },
        { path: 'zona-licencia', name: 'zona-licencia', component: () => import('@/views/modules/padron_licencias/ZonaLicencia.vue') },
        { path: 'privilegios', name: 'privilegios', component: () => import('@/views/modules/padron_licencias/privilegios.vue') },
        { path: 'unidad-img', name: 'unidad-img', component: () => import('@/views/modules/padron_licencias/UnidadImg.vue') },
        { path: 'dependencias', name: 'dependencias', component: () => import('@/views/modules/padron_licencias/dependenciasfrm.vue') },
        { path: 'estatus', name: 'estatus', component: () => import('@/views/modules/padron_licencias/estatusfrm.vue') },
        { path: 'giros-vigentes-cte-xgiro', name: 'giros-vigentes-cte-xgiro', component: () => import('@/views/modules/padron_licencias/girosVigentesCteXgirofrm.vue') },
        { path: 'consulta-licencias-400', name: 'consulta-licencias-400', component: () => import('@/views/modules/padron_licencias/consLic400frm.vue') },
        { path: 'consulta-anuncios-400', name: 'consulta-anuncios-400', component: () => import('@/views/modules/padron_licencias/consAnun400frm.vue') },
        { path: 'historial-bloqueo-domicilios', name: 'historial-bloqueo-domicilios', component: () => import('@/views/modules/padron_licencias/h_bloqueoDomiciliosfrm.vue') },
        { path: 'giros-con-adeudo', name: 'giros-con-adeudo', component: () => import('@/views/modules/padron_licencias/GirosDconAdeudofrm.vue') },
        { path: 'impresion-licencias-reglamentadas', name: 'impresion-licencias-reglamentadas', component: () => import('@/views/modules/padron_licencias/frmImpLicenciaReglamentada.vue') },
        { path: 'carga-imagenes', name: 'carga-imagenes', component: () => import('@/views/modules/padron_licencias/carga_imagen.vue') },
        { path: 'firma-digital', name: 'firma-digital', component: () => import('@/views/modules/padron_licencias/firma.vue') },
        { path: 'registro-historico', name: 'registro-historico', component: () => import('@/views/modules/padron_licencias/regHfrm.vue') },
        { path: 'sgc-v2', name: 'sgc-v2', component: () => import('@/views/modules/padron_licencias/SGCv2.vue') },
        { path: 'tdm-conexion', name: 'tdm-conexion', component: () => import('@/views/modules/padron_licencias/TDMConection.vue') },
        { path: 'navegador-web', name: 'navegador-web', component: () => import('@/views/modules/padron_licencias/webBrowser.vue') },
        { path: 'dialogo-giros', name: 'dialogo-giros', component: () => import('@/views/modules/padron_licencias/grs_dlg.vue') },
        { path: 'bienvenida', name: 'bienvenida', component: () => import('@/views/modules/padron_licencias/psplash.vue') },
        { path: 'imp-licencia-reglamentada', name: 'imp-licencia-reglamentada', component: () => import('@/views/modules/padron_licencias/ImpLicenciaReglamentada.vue') }
      ]
    },
    // PADRON LICENCIAS - Acceso (sin layout)
    { path: '/padron-licencias/acceso', name: 'padron-licencias-acceso', component: () => import('@/views/modules/padron_licencias/Acceso.vue'), meta: { requiresAuth: false } },
  ]
})

// Configurar guards globales para protección de rutas
setupGlobalGuards(router)

export default router
