// Configuración completa de todos los módulos con sus componentes reales
// Total: 639 componentes distribuidos en 10 módulos

export const estacionamientosRoutes = [
  { name: "acceso", path: "/estacionamientos/acceso", displayName: "Acceso" },
  { name: "aplicapgo_divadmin", path: "/estacionamientos/aplicapgo_divadmin", displayName: "Aplicapgo Divadmin" },
  { name: "bja_multiple", path: "/estacionamientos/bja_multiple", displayName: "Bja Multiple" },
  { name: "bja_multiple_ind", path: "/estacionamientos/bja_multiple_ind", displayName: "Bja Multiple Ind" },
  { name: "cga_arcedoex", path: "/estacionamientos/cga_arcedoex", displayName: "Cga Arcedoex" },
  { name: "consgral", path: "/estacionamientos/consgral", displayName: "Consgral" },
  { name: "consremesas", path: "/estacionamientos/consremesas", displayName: "Consremesas" },
  { name: "dm_crbos", path: "/estacionamientos/dm_crbos", displayName: "Dm Crbos" },
  { name: "dsdbgasto", path: "/estacionamientos/dsdbgasto", displayName: "Dsdbgasto" },
  { name: "dspasswords", path: "/estacionamientos/dspasswords", displayName: "Dspasswords" },
  { name: "frmmetrometers", path: "/estacionamientos/frmmetrometers", displayName: "Frmmetrometers" },
  { name: "gen_arcaltas", path: "/estacionamientos/gen_arcaltas", displayName: "Gen Arcaltas" },
  { name: "gen_arcdiario", path: "/estacionamientos/gen_arcdiario", displayName: "Gen Arcdiario" },
  { name: "gen_individual", path: "/estacionamientos/gen_individual", displayName: "Gen Individual" },
  { name: "gen_individual_b", path: "/estacionamientos/gen_individual_b", displayName: "Gen Individual B" },
  { name: "gen_pgosbanorte", path: "/estacionamientos/gen_pgosbanorte", displayName: "Gen Pgosbanorte" },
  { name: "mensaje", path: "/estacionamientos/mensaje", displayName: "Mensaje" },
  { name: "reactiva_folios", path: "/estacionamientos/reactiva_folios", displayName: "Reactiva Folios" },
  { name: "reportes_folios", path: "/estacionamientos/reportes_folios", displayName: "Reportes Folios" },
  { name: "sdmwebservice", path: "/estacionamientos/sdmwebservice", displayName: "Sdmwebservice" },
  { name: "sfolios_alta", path: "/estacionamientos/sfolios_alta", displayName: "Sfolios Alta" },
  { name: "sfrmmetrometers", path: "/estacionamientos/sfrmmetrometers", displayName: "Sfrmmetrometers" },
  { name: "sfrmprediocarto", path: "/estacionamientos/sfrmprediocarto", displayName: "Sfrmprediocarto" },
  { name: "sfrm_abc_propietario", path: "/estacionamientos/sfrm_abc_propietario", displayName: "Sfrm Abc Propietario" },
  { name: "sfrm_alta_ubicaciones", path: "/estacionamientos/sfrm_alta_ubicaciones", displayName: "Sfrm Alta Ubicaciones" },
  { name: "sfrm_aspecto", path: "/estacionamientos/sfrm_aspecto", displayName: "Sfrm Aspecto" },
  { name: "sfrm_chg_autorizadescto", path: "/estacionamientos/sfrm_chg_autorizadescto", displayName: "Sfrm Chg Autorizadescto" },
  { name: "sfrm_consultapublicos", path: "/estacionamientos/sfrm_consultapublicos", displayName: "Sfrm Consultapublicos" },
  { name: "sfrm_consulta_folios", path: "/estacionamientos/sfrm_consulta_folios", displayName: "Sfrm Consulta Folios" },
  { name: "sfrm_datos_oficio", path: "/estacionamientos/sfrm_datos_oficio", displayName: "Sfrm Datos Oficio" },
  { name: "sfrm_excconsulta", path: "/estacionamientos/sfrm_excconsulta", displayName: "Sfrm Excconsulta" },
  { name: "sfrm_exc_alta", path: "/estacionamientos/sfrm_exc_alta", displayName: "Sfrm Exc Alta" },
  { name: "sfrm_exc_mod_contrato", path: "/estacionamientos/sfrm_exc_mod_contrato", displayName: "Sfrm Exc Mod Contrato" },
  { name: "sfrm_menu", path: "/estacionamientos/sfrm_menu", displayName: "Sfrm Menu" },
  { name: "sfrm_modif_folios", path: "/estacionamientos/sfrm_modif_folios", displayName: "Sfrm Modif Folios" },
  { name: "sfrm_nva_calco", path: "/estacionamientos/sfrm_nva_calco", displayName: "Sfrm Nva Calco" },
  { name: "sfrm_pagosestadorel", path: "/estacionamientos/sfrm_pagosestadorel", displayName: "Sfrm Pagosestadorel" },
  { name: "sfrm_pasar_padron", path: "/estacionamientos/sfrm_pasar_padron", displayName: "Sfrm Pasar Padron" },
  { name: "sfrm_pdfviewer", path: "/estacionamientos/sfrm_pdfviewer", displayName: "Sfrm Pdfviewer" },
  { name: "sfrm_prop_exclusivo", path: "/estacionamientos/sfrm_prop_exclusivo", displayName: "Sfrm Prop Exclusivo" },
  { name: "sfrm_reportescalco", path: "/estacionamientos/sfrm_reportescalco", displayName: "Sfrm Reportescalco" },
  { name: "sfrm_reportes_exec", path: "/estacionamientos/sfrm_reportes_exec", displayName: "Sfrm Reportes Exec" },
  { name: "sfrm_report_pagos", path: "/estacionamientos/sfrm_report_pagos", displayName: "Sfrm Report Pagos" },
  { name: "sfrm_rep_folio", path: "/estacionamientos/sfrm_rep_folio", displayName: "Sfrm Rep Folio" },
  { name: "sfrm_transfolios", path: "/estacionamientos/sfrm_transfolios", displayName: "Sfrm Transfolios" },
  { name: "sfrm_trans_exclu", path: "/estacionamientos/sfrm_trans_exclu", displayName: "Sfrm Trans Exclu" },
  { name: "sfrm_trans_pub", path: "/estacionamientos/sfrm_trans_pub", displayName: "Sfrm Trans Pub" },
  { name: "sfrm_tr_estado_mpio", path: "/estacionamientos/sfrm_tr_estado_mpio", displayName: "Sfrm Tr Estado Mpio" },
  { name: "sfrm_upexclus", path: "/estacionamientos/sfrm_upexclus", displayName: "Sfrm Upexclus" },
  { name: "sfrm_up_pagos", path: "/estacionamientos/sfrm_up_pagos", displayName: "Sfrm Up Pagos" },
  { name: "sfrm_valet_paso", path: "/estacionamientos/sfrm_valet_paso", displayName: "Sfrm Valet Paso" },
  { name: "spubactualizacionfrm", path: "/estacionamientos/spubactualizacionfrm", displayName: "Spubactualizacionfrm" },
  { name: "spublicosnewfrm", path: "/estacionamientos/spublicosnewfrm", displayName: "Spublicosnewfrm" },
  { name: "spubreports", path: "/estacionamientos/spubreports", displayName: "Spubreports" },
  { name: "sqrp_esta01", path: "/estacionamientos/sqrp_esta01", displayName: "Sqrp Esta01" },
  { name: "sqrp_publicos", path: "/estacionamientos/sqrp_publicos", displayName: "Sqrp Publicos" },
  { name: "sqrp_relacion_folios", path: "/estacionamientos/sqrp_relacion_folios", displayName: "Sqrp Relacion Folios" },
  { name: "sqrt_imp_padron", path: "/estacionamientos/sqrt_imp_padron", displayName: "Sqrt Imp Padron" },
  { name: "srfrm_conci_banorte", path: "/estacionamientos/srfrm_conci_banorte", displayName: "Srfrm Conci Banorte" },
  { name: "unit1", path: "/estacionamientos/unit1", displayName: "Unit1" },
  { name: "unit9", path: "/estacionamientos/unit9", displayName: "Unit9" },
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "SistemaConveniosEstacionamientos", path: "/estacionamientos/sistemaconveniosestacionamientos", displayName: "🆕 Sistema Integral de Convenios", isNew: false },
  { name: "SistemaApremiosEstacionamientos", path: "/estacionamientos/sistemaapremiosestacionamientos", displayName: "🆕 Sistema Integral de Apremios", isNew: false },
  { name: "SistemaDescuentosConversion", path: "/estacionamientos/sistemadescuentosconversion", displayName: "🆕 Sistema de Descuentos y Conversión", isNew: false },
]

export const aseoRoutes = [
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "SistemaConveniosAseo", path: "/aseo/sistemaconveniosaseo", displayName: "🆕 Sistema Integral de Convenios", isNew: false },
  { name: "SistemaApremiosAseo", path: "/aseo/sistemaapremiosaseo", displayName: "🆕 Sistema Integral de Apremios", isNew: false },
  { name: "SistemaDescuentosAseo", path: "/aseo/sistemadescuentosaseo", displayName: "🆕 Sistema de Descuentos y Conversión", isNew: false },
  { name: "FuncionesExcluidasAseo", path: "/aseo/funcionesexcluidasaseo", displayName: "🆕 Funciones Excluidas", isNew: false },
  // Componentes existentes
  { name: "abc_cves_operacion", path: "/aseo/abc_cves_operacion", displayName: "Abc Cves Operacion" },
  { name: "abc_empresas", path: "/aseo/abc_empresas", displayName: "Abc Empresas" },
  { name: "abc_gastos", path: "/aseo/abc_gastos", displayName: "Abc Gastos" },
  { name: "abc_recargos", path: "/aseo/abc_recargos", displayName: "Abc Recargos" },
  { name: "abc_recaudadoras", path: "/aseo/abc_recaudadoras", displayName: "Abc Recaudadoras" },
  { name: "abc_tipos_aseo", path: "/aseo/abc_tipos_aseo", displayName: "Abc Tipos Aseo" },
  { name: "abc_tipos_emp", path: "/aseo/abc_tipos_emp", displayName: "Abc Tipos Emp" },
  { name: "abc_und_recolec", path: "/aseo/abc_und_recolec", displayName: "Abc Und Recolec" },
  { name: "abc_zonas", path: "/aseo/abc_zonas", displayName: "Abc Zonas" },
  { name: "actcont_cr", path: "/aseo/actcont_cr", displayName: "Actcont Cr" },
  { name: "adeudoscn_cond", path: "/aseo/adeudoscn_cond", displayName: "Adeudoscn Cond" },
  { name: "adeudosest", path: "/aseo/adeudosest", displayName: "Adeudosest" },
  { name: "adeudosexe_del", path: "/aseo/adeudosexe_del", displayName: "Adeudosexe Del" },
  { name: "adeudosmult_ins", path: "/aseo/adeudosmult_ins", displayName: "Adeudosmult Ins" },
  { name: "adeudos_carga", path: "/aseo/adeudos_carga", displayName: "Adeudos Carga" },
  { name: "adeudos_edocta", path: "/aseo/adeudos_edocta", displayName: "Adeudos Edocta" },
  { name: "adeudos_ins", path: "/aseo/adeudos_ins", displayName: "Adeudos Ins" },
  { name: "adeudos_nvo", path: "/aseo/adeudos_nvo", displayName: "Adeudos Nvo" },
  { name: "adeudos_opcmult", path: "/aseo/adeudos_opcmult", displayName: "Adeudos Opcmult" },
  { name: "adeudos_pag", path: "/aseo/adeudos_pag", displayName: "Adeudos Pag" },
  { name: "adeudos_pagmult", path: "/aseo/adeudos_pagmult", displayName: "Adeudos Pagmult" },
  { name: "adeudos_pagupdper", path: "/aseo/adeudos_pagupdper", displayName: "Adeudos Pagupdper" },
  { name: "adeudos_updexed", path: "/aseo/adeudos_updexed", displayName: "Adeudos Updexed" },
  { name: "adeudos_venc", path: "/aseo/adeudos_venc", displayName: "Adeudos Venc" },
  { name: "aplicamultasnormal", path: "/aseo/aplicamultasnormal", displayName: "Aplicamultasnormal" },
  { name: "cons_cves_operacion", path: "/aseo/cons_cves_operacion", displayName: "Cons Cves Operacion" },
  { name: "cons_empresas", path: "/aseo/cons_empresas", displayName: "Cons Empresas" },
  { name: "cons_tipos_aseo", path: "/aseo/cons_tipos_aseo", displayName: "Cons Tipos Aseo" },
  { name: "cons_tipos_emp", path: "/aseo/cons_tipos_emp", displayName: "Cons Tipos Emp" },
  { name: "cons_und_recolec", path: "/aseo/cons_und_recolec", displayName: "Cons Und Recolec" },
  { name: "cons_zonas", path: "/aseo/cons_zonas", displayName: "Cons Zonas" },
  { name: "contratos", path: "/aseo/contratos", displayName: "Contratos" },
  { name: "contratosest", path: "/aseo/contratosest", displayName: "Contratosest" },
  { name: "contratos_adeudos", path: "/aseo/contratos_adeudos", displayName: "Contratos Adeudos" },
  { name: "contratos_cancela", path: "/aseo/contratos_cancela", displayName: "Contratos Cancela" },
  { name: "contratos_cons", path: "/aseo/contratos_cons", displayName: "Contratos Cons" },
  { name: "contratos_consulta", path: "/aseo/contratos_consulta", displayName: "Contratos Consulta" },
  { name: "contratos_cons_admin", path: "/aseo/contratos_cons_admin", displayName: "Contratos Cons Admin" },
  { name: "contratos_cons_cont", path: "/aseo/contratos_cons_cont", displayName: "Contratos Cons Cont" },
  { name: "contratos_cons_contasc", path: "/aseo/contratos_cons_contasc", displayName: "Contratos Cons Contasc" },
  { name: "contratos_cons_dom", path: "/aseo/contratos_cons_dom", displayName: "Contratos Cons Dom" },
  { name: "contratos_del", path: "/aseo/contratos_del", displayName: "Contratos Del" },
  { name: "contratos_estgral", path: "/aseo/contratos_estgral", displayName: "Contratos Estgral" },
  { name: "contratos_estgral2", path: "/aseo/contratos_estgral2", displayName: "Contratos Estgral2" },
  { name: "contratos_ins", path: "/aseo/contratos_ins", displayName: "Contratos Ins" },
  { name: "contratos_ins_b", path: "/aseo/contratos_ins_b", displayName: "Contratos Ins B" },
  { name: "contratos_upd", path: "/aseo/contratos_upd", displayName: "Contratos Upd" },
  { name: "contratos_updxcont", path: "/aseo/contratos_updxcont", displayName: "Contratos Updxcont" },
  { name: "contratos_upd_01", path: "/aseo/contratos_upd_01", displayName: "Contratos Upd 01" },
  { name: "contratos_upd_iniobl", path: "/aseo/contratos_upd_iniobl", displayName: "Contratos Upd Iniobl" },
  { name: "contratos_upd_periodo", path: "/aseo/contratos_upd_periodo", displayName: "Contratos Upd Periodo" },
  { name: "contratos_upd_und", path: "/aseo/contratos_upd_und", displayName: "Contratos Upd Und" },
  { name: "contratos_upd_undc", path: "/aseo/contratos_upd_undc", displayName: "Contratos Upd Undc" },
  { name: "ctrol_imp_cat", path: "/aseo/ctrol_imp_cat", displayName: "Ctrol Imp Cat" },
  { name: "datosconvenio", path: "/aseo/datosconvenio", displayName: "Datosconvenio" },
  { name: "dscto_p_pago", path: "/aseo/dscto_p_pago", displayName: "Dscto P Pago" },
  { name: "ejercicios_ins", path: "/aseo/ejercicios_ins", displayName: "Ejercicios Ins" },
  { name: "empresas_contratos", path: "/aseo/empresas_contratos", displayName: "Empresas Contratos" },
  { name: "frmrep_und_recolec", path: "/aseo/frmrep_und_recolec", displayName: "Frmrep Und Recolec" },
  { name: "licencias_relacionadas", path: "/aseo/licencias_relacionadas", displayName: "Licencias Relacionadas" },
  { name: "mannto_empresas", path: "/aseo/mannto_empresas", displayName: "Mannto Empresas" },
  { name: "mannto_gastos", path: "/aseo/mannto_gastos", displayName: "Mannto Gastos" },
  { name: "mannto_operaciones", path: "/aseo/mannto_operaciones", displayName: "Mannto Operaciones" },
  { name: "mannto_recargos", path: "/aseo/mannto_recargos", displayName: "Mannto Recargos" },
  { name: "mannto_recaudadoras", path: "/aseo/mannto_recaudadoras", displayName: "Mannto Recaudadoras" },
  { name: "mannto_tipos_aseo", path: "/aseo/mannto_tipos_aseo", displayName: "Mannto Tipos Aseo" },
  { name: "mannto_tipos_emp", path: "/aseo/mannto_tipos_emp", displayName: "Mannto Tipos Emp" },
  { name: "mannto_und_recolec", path: "/aseo/mannto_und_recolec", displayName: "Mannto Und Recolec" },
  { name: "mannto_zonas", path: "/aseo/mannto_zonas", displayName: "Mannto Zonas" },
  { name: "menu", path: "/aseo/menu", displayName: "Menu" },
  { name: "pagos_cons_cont", path: "/aseo/pagos_cons_cont", displayName: "Pagos Cons Cont" },
  { name: "pagos_cons_contasc", path: "/aseo/pagos_cons_contasc", displayName: "Pagos Cons Contasc" },
  { name: "pagos_con_fpgo", path: "/aseo/pagos_con_fpgo", displayName: "Pagos Con Fpgo" },
  { name: "prueba", path: "/aseo/prueba", displayName: "Prueba" },
  { name: "rep_adeudcond", path: "/aseo/rep_adeudcond", displayName: "Rep Adeudcond" },
  { name: "rep_adeudos", path: "/aseo/rep_adeudos", displayName: "Rep Adeudos" },
  { name: "rep_contratos", path: "/aseo/rep_contratos", displayName: "Rep Contratos" },
  { name: "rep_empresas", path: "/aseo/rep_empresas", displayName: "Rep Empresas" },
  { name: "rep_padroncontratos", path: "/aseo/rep_padroncontratos", displayName: "Rep Padroncontratos" },
  { name: "rep_recaudadoras", path: "/aseo/rep_recaudadoras", displayName: "Rep Recaudadoras" },
  { name: "rep_tipos_aseo", path: "/aseo/rep_tipos_aseo", displayName: "Rep Tipos Aseo" },
  { name: "rep_tipos_emp", path: "/aseo/rep_tipos_emp", displayName: "Rep Tipos Emp" },
  { name: "rep_zonas", path: "/aseo/rep_zonas", displayName: "Rep Zonas" },
  { name: "reqscons", path: "/aseo/reqscons", displayName: "Reqscons" },
  { name: "sdm_procesos", path: "/aseo/sdm_procesos", displayName: "Sdm Procesos" },
  { name: "sqrptadeudos", path: "/aseo/sqrptadeudos", displayName: "Sqrptadeudos" },
  { name: "sqrptadeudoscond", path: "/aseo/sqrptadeudoscond", displayName: "Sqrptadeudoscond" },
  { name: "sqrptadeudosvenc", path: "/aseo/sqrptadeudosvenc", displayName: "Sqrptadeudosvenc" },
  { name: "sqrptcontratos", path: "/aseo/sqrptcontratos", displayName: "Sqrptcontratos" },
  { name: "sqrptcontratos_det", path: "/aseo/sqrptcontratos_det", displayName: "Sqrptcontratos Det" },
  { name: "sqrptcontratos_est", path: "/aseo/sqrptcontratos_est", displayName: "Sqrptcontratos Est" },
  { name: "sqrptcontratos_estgral", path: "/aseo/sqrptcontratos_estgral", displayName: "Sqrptcontratos Estgral" },
  { name: "sqrptcves_operacion", path: "/aseo/sqrptcves_operacion", displayName: "Sqrptcves Operacion" },
  { name: "sqrptempresas", path: "/aseo/sqrptempresas", displayName: "Sqrptempresas" },
  { name: "sqrptpagosxcontrato", path: "/aseo/sqrptpagosxcontrato", displayName: "Sqrptpagosxcontrato" },
  { name: "sqrptrecaudadoras", path: "/aseo/sqrptrecaudadoras", displayName: "Sqrptrecaudadoras" },
  { name: "sqrpttipos_aseo", path: "/aseo/sqrpttipos_aseo", displayName: "Sqrpttipos Aseo" },
  { name: "sqrpttipos_empresas", path: "/aseo/sqrpttipos_empresas", displayName: "Sqrpttipos Empresas" },
  { name: "sqrptund_recolec", path: "/aseo/sqrptund_recolec", displayName: "Sqrptund Recolec" },
  { name: "sqrptzonas", path: "/aseo/sqrptzonas", displayName: "Sqrptzonas" },
  { name: "udm_procesos", path: "/aseo/udm_procesos", displayName: "Udm Procesos" },
  { name: "unacceso", path: "/aseo/unacceso", displayName: "Unacceso" },
  { name: "unit1", path: "/aseo/unit1", displayName: "Unit1" },
]

export const mercadosRoutes = [
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN - MERCADOS
  { name: "SistemaConveniosMercados", path: "/mercados/sistemaconveniosmercados", displayName: "🆕 Sistema Convenios Integral", isNew: false },
  { name: "FuncionesExcluidasMercados", path: "/mercados/funcionesexcluidas", displayName: "🚫 Funciones Excluidas", isNew: false },
  // Componentes existentes
  { name: "acceso", path: "/mercados/acceso", displayName: "Acceso" },
  { name: "adeenergiagrl", path: "/mercados/adeenergiagrl", displayName: "Adeenergiagrl" },
  { name: "adegloballocales", path: "/mercados/adegloballocales", displayName: "Adegloballocales" },
  { name: "adeudosenergia", path: "/mercados/adeudosenergia", displayName: "Adeudosenergia" },
  { name: "adeudoslocales", path: "/mercados/adeudoslocales", displayName: "Adeudoslocales" },
  { name: "adeudoslocgrl", path: "/mercados/adeudoslocgrl", displayName: "Adeudoslocgrl" },
  { name: "altapagos", path: "/mercados/altapagos", displayName: "Altapagos" },
  { name: "altapagosenergia", path: "/mercados/altapagosenergia", displayName: "Altapagosenergia" },
  { name: "autcargapagos", path: "/mercados/autcargapagos", displayName: "Autcargapagos" },
  { name: "autcargapagosmtto", path: "/mercados/autcargapagosmtto", displayName: "Autcargapagosmtto" },
  { name: "cargadiversosesp", path: "/mercados/cargadiversosesp", displayName: "Cargadiversosesp" },
  { name: "cargapagenergia", path: "/mercados/cargapagenergia", displayName: "Cargapagenergia" },
  { name: "cargapagenergiaelec", path: "/mercados/cargapagenergiaelec", displayName: "Cargapagenergiaelec" },
  { name: "cargapagespecial", path: "/mercados/cargapagespecial", displayName: "Cargapagespecial" },
  { name: "cargapaglocales", path: "/mercados/cargapaglocales", displayName: "Cargapaglocales" },
  { name: "cargapagmercado", path: "/mercados/cargapagmercado", displayName: "Cargapagmercado" },
  { name: "cargapagostexto", path: "/mercados/cargapagostexto", displayName: "Cargapagostexto" },
  { name: "cargareqpagados", path: "/mercados/cargareqpagados", displayName: "Cargareqpagados" },
  { name: "cargatcultural", path: "/mercados/cargatcultural", displayName: "Cargatcultural" },
  { name: "catalogomercados", path: "/mercados/catalogomercados", displayName: "Catalogomercados" },
  { name: "catalogomntto", path: "/mercados/catalogomntto", displayName: "Catalogomntto" },
  { name: "categoria", path: "/mercados/categoria", displayName: "Categoria" },
  { name: "categoriamntto", path: "/mercados/categoriamntto", displayName: "Categoriamntto" },
  { name: "condonacion", path: "/mercados/condonacion", displayName: "Condonacion" },
  { name: "conscapturaenergia", path: "/mercados/conscapturaenergia", displayName: "Conscapturaenergia" },
  { name: "conscapturafecha", path: "/mercados/conscapturafecha", displayName: "Conscapturafecha" },
  { name: "conscapturafechaenergia", path: "/mercados/conscapturafechaenergia", displayName: "Conscapturafechaenergia" },
  { name: "conscapturamerc", path: "/mercados/conscapturamerc", displayName: "Conscapturamerc" },
  { name: "conscondonacion", path: "/mercados/conscondonacion", displayName: "Conscondonacion" },
  { name: "conscondonacionenergia", path: "/mercados/conscondonacionenergia", displayName: "Conscondonacionenergia" },
  { name: "conspagos", path: "/mercados/conspagos", displayName: "Conspagos" },
  { name: "conspagosenergia", path: "/mercados/conspagosenergia", displayName: "Conspagosenergia" },
  { name: "conspagoslocales", path: "/mercados/conspagoslocales", displayName: "Conspagoslocales" },
  { name: "consrequerimientos", path: "/mercados/consrequerimientos", displayName: "Consrequerimientos" },
  { name: "consultadatosenergia", path: "/mercados/consultadatosenergia", displayName: "Consultadatosenergia" },
  { name: "consultadatoslocales", path: "/mercados/consultadatoslocales", displayName: "Consultadatoslocales" },
  { name: "consultageneral", path: "/mercados/consultageneral", displayName: "Consultageneral" },
  { name: "cuentapublica", path: "/mercados/cuentapublica", displayName: "Cuentapublica" },
  { name: "cuotasenergia", path: "/mercados/cuotasenergia", displayName: "Cuotasenergia" },
  { name: "cuotasenergiamntto", path: "/mercados/cuotasenergiamntto", displayName: "Cuotasenergiamntto" },
  { name: "cuotasmdo", path: "/mercados/cuotasmdo", displayName: "Cuotasmdo" },
  { name: "cuotasmdomntto", path: "/mercados/cuotasmdomntto", displayName: "Cuotasmdomntto" },
  { name: "cvecuota", path: "/mercados/cvecuota", displayName: "Cvecuota" },
  { name: "cvecuotamntto", path: "/mercados/cvecuotamntto", displayName: "Cvecuotamntto" },
  { name: "cvediferencias", path: "/mercados/cvediferencias", displayName: "Cvediferencias" },
  { name: "cvedifermntto", path: "/mercados/cvedifermntto", displayName: "Cvedifermntto" },
  { name: "datosconvenio", path: "/mercados/datosconvenio", displayName: "Datosconvenio" },
  { name: "datosindividuales", path: "/mercados/datosindividuales", displayName: "Datosindividuales" },
  { name: "datosmovimientos", path: "/mercados/datosmovimientos", displayName: "Datosmovimientos" },
  { name: "datosrequerimientos", path: "/mercados/datosrequerimientos", displayName: "Datosrequerimientos" },
  { name: "emisionenergia", path: "/mercados/emisionenergia", displayName: "Emisionenergia" },
  { name: "emisionlibertad", path: "/mercados/emisionlibertad", displayName: "Emisionlibertad" },
  { name: "emisionlocales", path: "/mercados/emisionlocales", displayName: "Emisionlocales" },
  { name: "energiamodif", path: "/mercados/energiamodif", displayName: "Energiamodif" },
  { name: "energiamtto", path: "/mercados/energiamtto", displayName: "Energiamtto" },
  { name: "estadisticas", path: "/mercados/estadisticas", displayName: "Estadisticas" },
  { name: "estadpagosyadeudos", path: "/mercados/estadpagosyadeudos", displayName: "Estadpagosyadeudos" },
  { name: "fechadescuento", path: "/mercados/fechadescuento", displayName: "Fechadescuento" },
  { name: "fechasdescuentomntto", path: "/mercados/fechasdescuentomntto", displayName: "Fechasdescuentomntto" },
  { name: "ingresocaptura", path: "/mercados/ingresocaptura", displayName: "Ingresocaptura" },
  { name: "ingresolib", path: "/mercados/ingresolib", displayName: "Ingresolib" },
  { name: "listadoslocales", path: "/mercados/listadoslocales", displayName: "Listadoslocales" },
  { name: "localesmodif", path: "/mercados/localesmodif", displayName: "Localesmodif" },
  { name: "localesmtto", path: "/mercados/localesmtto", displayName: "Localesmtto" },
  { name: "menu", path: "/mercados/menu", displayName: "Menu" },
  { name: "modulobd", path: "/mercados/modulobd", displayName: "Modulobd" },
  { name: "padronenergia", path: "/mercados/padronenergia", displayName: "Padronenergia" },
  { name: "padronglobal", path: "/mercados/padronglobal", displayName: "Padronglobal" },
  { name: "padronlocales", path: "/mercados/padronlocales", displayName: "Padronlocales" },
  { name: "pagosdifingresos", path: "/mercados/pagosdifingresos", displayName: "Pagosdifingresos" },
  { name: "pagosenecons", path: "/mercados/pagosenecons", displayName: "Pagosenecons" },
  { name: "pagosindividual", path: "/mercados/pagosindividual", displayName: "Pagosindividual" },
  { name: "pagoslocgrl", path: "/mercados/pagoslocgrl", displayName: "Pagoslocgrl" },
  { name: "pasoadeudos", path: "/mercados/pasoadeudos", displayName: "Pasoadeudos" },
  { name: "pasoene", path: "/mercados/pasoene", displayName: "Pasoene" },
  { name: "pasomdos", path: "/mercados/pasomdos", displayName: "Pasomdos" },
  { name: "prescripcion", path: "/mercados/prescripcion", displayName: "Prescripcion" },
  { name: "recargos", path: "/mercados/recargos", displayName: "Recargos" },
  { name: "recargosmntto", path: "/mercados/recargosmntto", displayName: "Recargosmntto" },
  { name: "rprtsalvadas", path: "/mercados/rprtsalvadas", displayName: "Rprtsalvadas" },
  { name: "rptadeenergiagrl", path: "/mercados/rptadeenergiagrl", displayName: "Rptadeenergiagrl" },
  { name: "rptadeudosabastos1998", path: "/mercados/rptadeudosabastos1998", displayName: "Rptadeudosabastos1998" },
  { name: "rptadeudosanteriores", path: "/mercados/rptadeudosanteriores", displayName: "Rptadeudosanteriores" },
  { name: "rptadeudosenergia", path: "/mercados/rptadeudosenergia", displayName: "Rptadeudosenergia" },
  { name: "rptadeudoslocales", path: "/mercados/rptadeudoslocales", displayName: "Rptadeudoslocales" },
  { name: "rptcaratuladatos", path: "/mercados/rptcaratuladatos", displayName: "Rptcaratuladatos" },
  { name: "rptcaratulaenergia", path: "/mercados/rptcaratulaenergia", displayName: "Rptcaratulaenergia" },
  { name: "rptcatalogomerc", path: "/mercados/rptcatalogomerc", displayName: "Rptcatalogomerc" },
  { name: "rptcuentapublica", path: "/mercados/rptcuentapublica", displayName: "Rptcuentapublica" },
  { name: "rptdesgloceadeporimporte", path: "/mercados/rptdesgloceadeporimporte", displayName: "Rptdesgloceadeporimporte" },
  { name: "rptemisionenergia", path: "/mercados/rptemisionenergia", displayName: "Rptemisionenergia" },
  { name: "rptemisionlaser", path: "/mercados/rptemisionlaser", displayName: "Rptemisionlaser" },
  { name: "rptemisionlocales", path: "/mercados/rptemisionlocales", displayName: "Rptemisionlocales" },
  { name: "rptemisionrbosabastos", path: "/mercados/rptemisionrbosabastos", displayName: "Rptemisionrbosabastos" },
  { name: "rptestadisticaadeudos", path: "/mercados/rptestadisticaadeudos", displayName: "Rptestadisticaadeudos" },
  { name: "rptestadpagosyadeudos", path: "/mercados/rptestadpagosyadeudos", displayName: "Rptestadpagosyadeudos" },
  { name: "rptfacturaemision", path: "/mercados/rptfacturaemision", displayName: "Rptfacturaemision" },
  { name: "rptfacturaenergia", path: "/mercados/rptfacturaenergia", displayName: "Rptfacturaenergia" },
  { name: "rptingresozonificado", path: "/mercados/rptingresozonificado", displayName: "Rptingresozonificado" },
  { name: "rptmovimientos", path: "/mercados/rptmovimientos", displayName: "Rptmovimientos" },
  { name: "rptpadronenergia", path: "/mercados/rptpadronenergia", displayName: "Rptpadronenergia" },
  { name: "rptpadronglobal", path: "/mercados/rptpadronglobal", displayName: "Rptpadronglobal" },
  { name: "rptpadronlocales", path: "/mercados/rptpadronlocales", displayName: "Rptpadronlocales" },
  { name: "rptpagoslocales", path: "/mercados/rptpagoslocales", displayName: "Rptpagoslocales" },
  { name: "secciones", path: "/mercados/secciones", displayName: "Secciones" },
  { name: "seccionesmntto", path: "/mercados/seccionesmntto", displayName: "Seccionesmntto" },
  { name: "trdocumentos", path: "/mercados/trdocumentos", displayName: "Trdocumentos" },
]

export const recaudadoraRoutes = [
  { name: "actualizafechaempresas", path: "/recaudadora/actualizafechaempresas", displayName: "Actualizafechaempresas" },
  { name: "aplicasdosfavor", path: "/recaudadora/aplicasdosfavor", displayName: "Aplicasdosfavor" },
  { name: "autdescto", path: "/recaudadora/autdescto", displayName: "Autdescto" },
  { name: "bloqctasreqfrm", path: "/recaudadora/bloqctasreqfrm", displayName: "Bloqctasreqfrm" },
  { name: "bloqueomulta", path: "/recaudadora/bloqueomulta", displayName: "Bloqueomulta" },
  { name: "busque", path: "/recaudadora/busque", displayName: "Busque" },
  { name: "canc", path: "/recaudadora/canc", displayName: "Canc" },
  { name: "capturadif", path: "/recaudadora/capturadif", displayName: "Capturadif" },
  { name: "cartainvitacion", path: "/recaudadora/cartainvitacion", displayName: "Cartainvitacion" },
  { name: "catastrodm", path: "/recaudadora/catastrodm", displayName: "Catastrodm" },
  { name: "centrosfrm", path: "/recaudadora/centrosfrm", displayName: "Centrosfrm" },
  { name: "codificafrm", path: "/recaudadora/codificafrm", displayName: "Codificafrm" },
  { name: "conscentrosfrm", path: "/recaudadora/conscentrosfrm", displayName: "Conscentrosfrm" },
  { name: "consdesc", path: "/recaudadora/consdesc", displayName: "Consdesc" },
  { name: "consescrit400", path: "/recaudadora/consescrit400", displayName: "Consescrit400" },
  { name: "consmulpagos", path: "/recaudadora/consmulpagos", displayName: "Consmulpagos" },
  { name: "consobsmulfrm", path: "/recaudadora/consobsmulfrm", displayName: "Consobsmulfrm" },
  { name: "consreq400", path: "/recaudadora/consreq400", displayName: "Consreq400" },
  { name: "consultapredial", path: "/recaudadora/consultapredial", displayName: "Consultapredial" },
  { name: "dderechoslic", path: "/recaudadora/dderechoslic", displayName: "Dderechoslic" },
  { name: "descderechosmerc", path: "/recaudadora/descderechosmerc", displayName: "Descderechosmerc" },
  { name: "descmultampalfrm", path: "/recaudadora/descmultampalfrm", displayName: "Descmultampalfrm" },
  { name: "descpredfrm", path: "/recaudadora/descpredfrm", displayName: "Descpredfrm" },
  { name: "desctorec", path: "/recaudadora/desctorec", displayName: "Desctorec" },
  { name: "drecgofosa", path: "/recaudadora/drecgofosa", displayName: "Drecgofosa" },
  { name: "drecgolic", path: "/recaudadora/drecgolic", displayName: "Drecgolic" },
  { name: "drecgootrasobligaciones", path: "/recaudadora/drecgootrasobligaciones", displayName: "Drecgootrasobligaciones" },
  { name: "drecgotrans", path: "/recaudadora/drecgotrans", displayName: "Drecgotrans" },
  { name: "ejecutores", path: "/recaudadora/ejecutores", displayName: "Ejecutores" },
  { name: "empresas", path: "/recaudadora/empresas", displayName: "Empresas" },
  { name: "entregafrm", path: "/recaudadora/entregafrm", displayName: "Entregafrm" },
  { name: "estadreq", path: "/recaudadora/estadreq", displayName: "Estadreq" },
  { name: "exclusivos_upd", path: "/recaudadora/exclusivos_upd", displayName: "Exclusivos Upd" },
  { name: "extractosrpt", path: "/recaudadora/extractosrpt", displayName: "Extractosrpt" },
  { name: "firmaelectronica", path: "/recaudadora/firmaelectronica", displayName: "Firmaelectronica" },
  { name: "folmulta", path: "/recaudadora/folmulta", displayName: "Folmulta" },
  { name: "frmeje", path: "/recaudadora/frmeje", displayName: "Frmeje" },
  { name: "frmpol", path: "/recaudadora/frmpol", displayName: "Frmpol" },
  { name: "gastostransmision", path: "/recaudadora/gastostransmision", displayName: "Gastostransmision" },
  { name: "hastafrm", path: "/recaudadora/hastafrm", displayName: "Hastafrm" },
  { name: "impreqcvecat", path: "/recaudadora/impreqcvecat", displayName: "Impreqcvecat" },
  { name: "impresionnva", path: "/recaudadora/impresionnva", displayName: "Impresionnva" },
  { name: "imprimedesctos", path: "/recaudadora/imprimedesctos", displayName: "Imprimedesctos" },
  { name: "ipor", path: "/recaudadora/ipor", displayName: "Ipor" },
  { name: "leyesfrm", path: "/recaudadora/leyesfrm", displayName: "Leyesfrm" },
  { name: "licenciamicrogenerador", path: "/recaudadora/licenciamicrogenerador", displayName: "Licenciamicrogenerador" },
  { name: "licenciamicrogeneradorecologia", path: "/recaudadora/licenciamicrogeneradorecologia", displayName: "Licenciamicrogeneradorecologia" },
  { name: "ligapago", path: "/recaudadora/ligapago", displayName: "Ligapago" },
  { name: "ligapagotra", path: "/recaudadora/ligapagotra", displayName: "Ligapagotra" },
  { name: "listadiferencias", path: "/recaudadora/listadiferencias", displayName: "Listadiferencias" },
  { name: "listadomultiple", path: "/recaudadora/listadomultiple", displayName: "Listadomultiple" },
  { name: "listana", path: "/recaudadora/listana", displayName: "Listana" },
  { name: "listanotificacionesfrm", path: "/recaudadora/listanotificacionesfrm", displayName: "Listanotificacionesfrm" },
  { name: "listareq", path: "/recaudadora/listareq", displayName: "Listareq" },
  { name: "listchq", path: "/recaudadora/listchq", displayName: "Listchq" },
  { name: "listdesctomultafrm", path: "/recaudadora/listdesctomultafrm", displayName: "Listdesctomultafrm" },
  { name: "modifmasiva", path: "/recaudadora/modifmasiva", displayName: "Modifmasiva" },
  { name: "multas400frm", path: "/recaudadora/multas400frm", displayName: "Multas400frm" },
  { name: "multasdm", path: "/recaudadora/multasdm", displayName: "Multasdm" },
  { name: "multasfrm", path: "/recaudadora/multasfrm", displayName: "Multasfrm" },
  { name: "multasfrmcalif", path: "/recaudadora/multasfrmcalif", displayName: "Multasfrmcalif" },
  { name: "newsfrm", path: "/recaudadora/newsfrm", displayName: "Newsfrm" },
  { name: "otorgadescto", path: "/recaudadora/otorgadescto", displayName: "Otorgadescto" },
  { name: "pagalicfrm", path: "/recaudadora/pagalicfrm", displayName: "Pagalicfrm" },
  { name: "pagosdivfrm", path: "/recaudadora/pagosdivfrm", displayName: "Pagosdivfrm" },
  { name: "pagosespe", path: "/recaudadora/pagosespe", displayName: "Pagosespe" },
  { name: "pagosmultfrm", path: "/recaudadora/pagosmultfrm", displayName: "Pagosmultfrm" },
  { name: "periodoinicial", path: "/recaudadora/periodoinicial", displayName: "Periodoinicial" },
  { name: "polcon", path: "/recaudadora/polcon", displayName: "Polcon" },
  { name: "prepagofrm", path: "/recaudadora/prepagofrm", displayName: "Prepagofrm" },
  { name: "pres", path: "/recaudadora/pres", displayName: "Pres" },
  { name: "propuestatab", path: "/recaudadora/propuestatab", displayName: "Propuestatab" },
  { name: "proyecfrm", path: "/recaudadora/proyecfrm", displayName: "Proyecfrm" },
  { name: "pruebacalcas", path: "/recaudadora/pruebacalcas", displayName: "Pruebacalcas" },
  { name: "psplash", path: "/recaudadora/psplash", displayName: "Psplash" },
  { name: "publicos_upd", path: "/recaudadora/publicos_upd", displayName: "Publicos Upd" },
  { name: "reg", path: "/recaudadora/reg", displayName: "Reg" },
  { name: "reghfrm", path: "/recaudadora/reghfrm", displayName: "Reghfrm" },
  { name: "regsecymas", path: "/recaudadora/regsecymas", displayName: "Regsecymas" },
  { name: "reimpfrm", path: "/recaudadora/reimpfrm", displayName: "Reimpfrm" },
  { name: "relmes", path: "/recaudadora/relmes", displayName: "Relmes" },
  { name: "repavance", path: "/recaudadora/repavance", displayName: "Repavance" },
  { name: "repdescimpto", path: "/recaudadora/repdescimpto", displayName: "Repdescimpto" },
  { name: "repmultampalfrm", path: "/recaudadora/repmultampalfrm", displayName: "Repmultampalfrm" },
  { name: "repoper", path: "/recaudadora/repoper", displayName: "Repoper" },
  { name: "req", path: "/recaudadora/req", displayName: "Req" },
  { name: "reqctascanfrm", path: "/recaudadora/reqctascanfrm", displayName: "Reqctascanfrm" },
  { name: "reqfrm", path: "/recaudadora/reqfrm", displayName: "Reqfrm" },
  { name: "reqmultas400frm", path: "/recaudadora/reqmultas400frm", displayName: "Reqmultas400frm" },
  { name: "reqpromocion", path: "/recaudadora/reqpromocion", displayName: "Reqpromocion" },
  { name: "reqtrans", path: "/recaudadora/reqtrans", displayName: "Reqtrans" },
  { name: "requerimientosdm", path: "/recaudadora/requerimientosdm", displayName: "Requerimientosdm" },
  { name: "requerxcvecat", path: "/recaudadora/requerxcvecat", displayName: "Requerxcvecat" },
  { name: "resolucionjuez", path: "/recaudadora/resolucionjuez", displayName: "Resolucionjuez" },
  { name: "sdosfavordm", path: "/recaudadora/sdosfavordm", displayName: "Sdosfavordm" },
  { name: "sdosfavor_ctrlexp", path: "/recaudadora/sdosfavor_ctrlexp", displayName: "Sdosfavor Ctrlexp" },
  { name: "sdosfavor_pagos", path: "/recaudadora/sdosfavor_pagos", displayName: "Sdosfavor Pagos" },
  { name: "sfrm_calificacionqr", path: "/recaudadora/sfrm_calificacionqr", displayName: "Sfrm Calificacionqr" },
  { name: "sfrm_chgpass", path: "/recaudadora/sfrm_chgpass", displayName: "Sfrm Chgpass" },
  { name: "sfrm_prescrip_sec01", path: "/recaudadora/sfrm_prescrip_sec01", displayName: "Sfrm Prescrip Sec01" },
  { name: "sgcv2", path: "/recaudadora/sgcv2", displayName: "Sgcv2" },
  { name: "sinligarfrm", path: "/recaudadora/sinligarfrm", displayName: "Sinligarfrm" },
  { name: "solsdosfavor", path: "/recaudadora/solsdosfavor", displayName: "Solsdosfavor" },
  { name: "tdmconection", path: "/recaudadora/tdmconection", displayName: "Tdmconection" },
  { name: "trasladosfrm", path: "/recaudadora/trasladosfrm", displayName: "Trasladosfrm" },
  { name: "ubicodifica", path: "/recaudadora/ubicodifica", displayName: "Ubicodifica" },
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "SistemaConveniosRecaudadora", path: "/recaudadora/sistemaconveniosrecaudadora", displayName: "🆕 Sistema Integral de Convenios", isNew: false },
  { name: "SistemaApremiosRecaudadora", path: "/recaudadora/sistemaapremiosrecaudadora", displayName: "🆕 Sistema Integral de Apremios", isNew: false },
  { name: "FuncionesExcluidasRecaudadora", path: "/recaudadora/funcionesexcluidasrecaudadora", displayName: "🆕 Funciones Excluidas", isNew: false },
]

export const tramiteTrunkRoutes = [
  { name: "abstenmov", path: "/tramite-trunk/abstenmov", displayName: "Abstenmov" },
  { name: "aprobaval", path: "/tramite-trunk/aprobaval", displayName: "Aprobaval" },
  { name: "areatitulofrm", path: "/tramite-trunk/areatitulofrm", displayName: "Areatitulofrm" },
  { name: "auttranspatfrm", path: "/tramite-trunk/auttranspatfrm", displayName: "Auttranspatfrm" },
  { name: "avaexter", path: "/tramite-trunk/avaexter", displayName: "Avaexter" },
  { name: "avisofrm", path: "/tramite-trunk/avisofrm", displayName: "Avisofrm" },
  { name: "busque", path: "/tramite-trunk/busque", displayName: "Busque" },
  { name: "cambiaporcentajecondu", path: "/tramite-trunk/cambiaporcentajecondu", displayName: "Cambiaporcentajecondu" },
  { name: "captcontribfrm", path: "/tramite-trunk/captcontribfrm", displayName: "Captcontribfrm" },
  { name: "catastrodm", path: "/tramite-trunk/catastrodm", displayName: "Catastrodm" },
  { name: "ccuenta", path: "/tramite-trunk/ccuenta", displayName: "Ccuenta" },
  { name: "comprofrm", path: "/tramite-trunk/comprofrm", displayName: "Comprofrm" },
  { name: "condominiofrm", path: "/tramite-trunk/condominiofrm", displayName: "Condominiofrm" },
  { name: "conduenosfrm", path: "/tramite-trunk/conduenosfrm", displayName: "Conduenosfrm" },
  { name: "conduenosfrmold", path: "/tramite-trunk/conduenosfrmold", displayName: "Conduenosfrmold" },
  { name: "consescrit400", path: "/tramite-trunk/consescrit400", displayName: "Consescrit400" },
  { name: "consimppat", path: "/tramite-trunk/consimppat", displayName: "Consimppat" },
  { name: "conspag400", path: "/tramite-trunk/conspag400", displayName: "Conspag400" },
  { name: "consreq400", path: "/tramite-trunk/consreq400", displayName: "Consreq400" },
  { name: "constp", path: "/tramite-trunk/constp", displayName: "Constp" },
  { name: "constpat", path: "/tramite-trunk/constpat", displayName: "Constpat" },
  { name: "constpat400", path: "/tramite-trunk/constpat400", displayName: "Constpat400" },
  { name: "consuem400", path: "/tramite-trunk/consuem400", displayName: "Consuem400" },
  { name: "consultapredial", path: "/tramite-trunk/consultapredial", displayName: "Consultapredial" },
  { name: "consultatransmfrm", path: "/tramite-trunk/consultatransmfrm", displayName: "Consultatransmfrm" },
  { name: "contri", path: "/tramite-trunk/contri", displayName: "Contri" },
  { name: "cvecatdupfrm", path: "/tramite-trunk/cvecatdupfrm", displayName: "Cvecatdupfrm" },
  { name: "cvecatfrm", path: "/tramite-trunk/cvecatfrm", displayName: "Cvecatfrm" },
  { name: "datostransmfrm", path: "/tramite-trunk/datostransmfrm", displayName: "Datostransmfrm" },
  { name: "eddatgralestrans", path: "/tramite-trunk/eddatgralestrans", displayName: "Eddatgralestrans" },
  { name: "edubica", path: "/tramite-trunk/edubica", displayName: "Edubica" },
  { name: "exenta", path: "/tramite-trunk/exenta", displayName: "Exenta" },
  { name: "extractosrpt", path: "/tramite-trunk/extractosrpt", displayName: "Extractosrpt" },
  { name: "frmconstglob", path: "/tramite-trunk/frmconstglob", displayName: "Frmconstglob" },
  { name: "frmindiv", path: "/tramite-trunk/frmindiv", displayName: "Frmindiv" },
  { name: "frmobserva", path: "/tramite-trunk/frmobserva", displayName: "Frmobserva" },
  { name: "funcion_abstencion", path: "/tramite-trunk/funcion_abstencion", displayName: "Funcion Abstencion" },
  { name: "hastafrm", path: "/tramite-trunk/hastafrm", displayName: "Hastafrm" },
  { name: "impno", path: "/tramite-trunk/impno", displayName: "Impno" },
  { name: "investctafrm", path: "/tramite-trunk/investctafrm", displayName: "Investctafrm" },
  { name: "listado", path: "/tramite-trunk/listado", displayName: "Listado" },
  { name: "loctp", path: "/tramite-trunk/loctp", displayName: "Loctp" },
  { name: "muestradupfrm", path: "/tramite-trunk/muestradupfrm", displayName: "Muestradupfrm" },
  { name: "observafrm", path: "/tramite-trunk/observafrm", displayName: "Observafrm" },
  { name: "observatransmfrm", path: "/tramite-trunk/observatransmfrm", displayName: "Observatransmfrm" },
  { name: "passpropietariofrm", path: "/tramite-trunk/passpropietariofrm", displayName: "Passpropietariofrm" },
  { name: "passwdfrm", path: "/tramite-trunk/passwdfrm", displayName: "Passwdfrm" },
  { name: "precep", path: "/tramite-trunk/precep", displayName: "Precep" },
  { name: "preferencialfrm", path: "/tramite-trunk/preferencialfrm", displayName: "Preferencialfrm" },
  { name: "prepagofrm", path: "/tramite-trunk/prepagofrm", displayName: "Prepagofrm" },
  { name: "pres", path: "/tramite-trunk/pres", displayName: "Pres" },
  { name: "propuestatab", path: "/tramite-trunk/propuestatab", displayName: "Propuestatab" },
  { name: "propuestatab1", path: "/tramite-trunk/propuestatab1", displayName: "Propuestatab1" },
  { name: "psplash", path: "/tramite-trunk/psplash", displayName: "Psplash" },
  { name: "rangoctasfrm", path: "/tramite-trunk/rangoctasfrm", displayName: "Rangoctasfrm" },
  { name: "reactivafrm", path: "/tramite-trunk/reactivafrm", displayName: "Reactivafrm" },
  { name: "rechazo", path: "/tramite-trunk/rechazo", displayName: "Rechazo" },
  { name: "reghfrm", path: "/tramite-trunk/reghfrm", displayName: "Reghfrm" },
  { name: "replegal", path: "/tramite-trunk/replegal", displayName: "Replegal" },
  { name: "sfrm_chgfirma", path: "/tramite-trunk/sfrm_chgfirma", displayName: "Sfrm Chgfirma" },
  { name: "sfrm_chgpass", path: "/tramite-trunk/sfrm_chgpass", displayName: "Sfrm Chgpass" },
  { name: "sgcv2", path: "/tramite-trunk/sgcv2", displayName: "Sgcv2" },
  { name: "tdmconection", path: "/tramite-trunk/tdmconection", displayName: "Tdmconection" },
  { name: "tramitedm", path: "/tramite-trunk/tramitedm", displayName: "Tramitedm" },
  { name: "umodcondofrm", path: "/tramite-trunk/umodcondofrm", displayName: "Umodcondofrm" },
  { name: "unit5", path: "/tramite-trunk/unit5", displayName: "Unit5" },
  { name: "valoresfrm", path: "/tramite-trunk/valoresfrm", displayName: "Valoresfrm" },
  { name: "valoresfrm_aux", path: "/tramite-trunk/valoresfrm_aux", displayName: "Valoresfrm Aux" },
]

export const conveniosRoutes = [
  { name: "acceso", path: "/convenios/acceso", displayName: "Acceso" },
  { name: "actualizacont", path: "/convenios/actualizacont", displayName: "Actualizacont" },
  { name: "actualizadevolucion", path: "/convenios/actualizadevolucion", displayName: "Actualizadevolucion" },
  { name: "actualizaplazo", path: "/convenios/actualizaplazo", displayName: "Actualizaplazo" },
  { name: "adeudoscontratos", path: "/convenios/adeudoscontratos", displayName: "Adeudoscontratos" },
  { name: "afectapagadmin", path: "/convenios/afectapagadmin", displayName: "Afectapagadmin" },
  { name: "altaconvdiversos", path: "/convenios/altaconvdiversos", displayName: "Altaconvdiversos" },
  { name: "altaconvenios", path: "/convenios/altaconvenios", displayName: "Altaconvenios" },
  { name: "altapagospredios", path: "/convenios/altapagospredios", displayName: "Altapagospredios" },
  { name: "ampliacionesmtto", path: "/convenios/ampliacionesmtto", displayName: "Ampliacionesmtto" },
  { name: "busca", path: "/convenios/busca", displayName: "Busca" },
  { name: "buscaregistromodulo", path: "/convenios/buscaregistromodulo", displayName: "Buscaregistromodulo" },
  { name: "calculorecargos", path: "/convenios/calculorecargos", displayName: "Calculorecargos" },
  { name: "calles", path: "/convenios/calles", displayName: "Calles" },
  { name: "callesmntto", path: "/convenios/callesmntto", displayName: "Callesmntto" },
  { name: "cancelacionmasiva", path: "/convenios/cancelacionmasiva", displayName: "Cancelacionmasiva" },
  { name: "cargapagdiversos", path: "/convenios/cargapagdiversos", displayName: "Cargapagdiversos" },
  { name: "colonias", path: "/convenios/colonias", displayName: "Colonias" },
  { name: "coloniasmntto", path: "/convenios/coloniasmntto", displayName: "Coloniasmntto" },
  { name: "conscontratos", path: "/convenios/conscontratos", displayName: "Conscontratos" },
  { name: "consdesgloce", path: "/convenios/consdesgloce", displayName: "Consdesgloce" },
  { name: "consindividual", path: "/convenios/consindividual", displayName: "Consindividual" },
  { name: "conspagcontratos", path: "/convenios/conspagcontratos", displayName: "Conspagcontratos" },
  { name: "conspagosdiversos", path: "/convenios/conspagosdiversos", displayName: "Conspagosdiversos" },
  { name: "conspagospredios", path: "/convenios/conspagospredios", displayName: "Conspagospredios" },
  { name: "conspredios", path: "/convenios/conspredios", displayName: "Conspredios" },
  { name: "consultaingreso", path: "/convenios/consultaingreso", displayName: "Consultaingreso" },
  { name: "consultanuevoplazo", path: "/convenios/consultanuevoplazo", displayName: "Consultanuevoplazo" },
  { name: "corregircaptura", path: "/convenios/corregircaptura", displayName: "Corregircaptura" },
  { name: "desgloceadeudosdiv", path: "/convenios/desgloceadeudosdiv", displayName: "Desgloceadeudosdiv" },
  { name: "desgloceparcialidades", path: "/convenios/desgloceparcialidades", displayName: "Desgloceparcialidades" },
  { name: "detalleadeudo", path: "/convenios/detalleadeudo", displayName: "Detalleadeudo" },
  { name: "detallepagos", path: "/convenios/detallepagos", displayName: "Detallepagos" },
  { name: "detallepagosconvpred", path: "/convenios/detallepagosconvpred", displayName: "Detallepagosconvpred" },
  { name: "detallepagosdiversos", path: "/convenios/detallepagosdiversos", displayName: "Detallepagosdiversos" },
  { name: "deudagrupo", path: "/convenios/deudagrupo", displayName: "Deudagrupo" },
  { name: "devolucionmtto", path: "/convenios/devolucionmtto", displayName: "Devolucionmtto" },
  { name: "edocuenta", path: "/convenios/edocuenta", displayName: "Edocuenta" },
  { name: "elaboraconvenios", path: "/convenios/elaboraconvenios", displayName: "Elaboraconvenios" },
  { name: "elaboroconvenio", path: "/convenios/elaboroconvenio", displayName: "Elaboroconvenio" },
  { name: "elaboromntto", path: "/convenios/elaboromntto", displayName: "Elaboromntto" },
  { name: "estadisticascontratos", path: "/convenios/estadisticascontratos", displayName: "Estadisticascontratos" },
  { name: "firmas", path: "/convenios/firmas", displayName: "Firmas" },
  { name: "firmasmntto", path: "/convenios/firmasmntto", displayName: "Firmasmntto" },
  { name: "imprimeoficio", path: "/convenios/imprimeoficio", displayName: "Imprimeoficio" },
  { name: "individualdiversos", path: "/convenios/individualdiversos", displayName: "Individualdiversos" },
  { name: "individualpredios", path: "/convenios/individualpredios", displayName: "Individualpredios" },
  { name: "intereses", path: "/convenios/intereses", displayName: "Intereses" },
  { name: "interesesmtto", path: "/convenios/interesesmtto", displayName: "Interesesmtto" },
  { name: "listadoconvdiversos", path: "/convenios/listadoconvdiversos", displayName: "Listadoconvdiversos" },
  { name: "mantpagoscontratos", path: "/convenios/mantpagoscontratos", displayName: "Mantpagoscontratos" },
  { name: "mensajes", path: "/convenios/mensajes", displayName: "Mensajes" },
  { name: "menu", path: "/convenios/menu", displayName: "Menu" },
  { name: "modifconvdiversos", path: "/convenios/modifconvdiversos", displayName: "Modifconvdiversos" },
  { name: "modulobd", path: "/convenios/modulobd", displayName: "Modulobd" },
  { name: "padronadeudos", path: "/convenios/padronadeudos", displayName: "Padronadeudos" },
  { name: "padronconvejec", path: "/convenios/padronconvejec", displayName: "Padronconvejec" },
  { name: "padronconvenios", path: "/convenios/padronconvenios", displayName: "Padronconvenios" },
  { name: "parcialidadesvencidas", path: "/convenios/parcialidadesvencidas", displayName: "Parcialidadesvencidas" },
  { name: "pasocontratos", path: "/convenios/pasocontratos", displayName: "Pasocontratos" },
  { name: "pasoconvdiversos", path: "/convenios/pasoconvdiversos", displayName: "Pasoconvdiversos" },
  { name: "pasopagos", path: "/convenios/pasopagos", displayName: "Pasopagos" },
  { name: "predial", path: "/convenios/predial", displayName: "Predial" },
  { name: "rprtsalvadas", path: "/convenios/rprtsalvadas", displayName: "Rprtsalvadas" },
  { name: "rptadeudocortemanzana", path: "/convenios/rptadeudocortemanzana", displayName: "Rptadeudocortemanzana" },
  { name: "rptadeudocortemanzanasaldoant", path: "/convenios/rptadeudocortemanzanasaldoant", displayName: "Rptadeudocortemanzanasaldoant" },
  { name: "rptadeudoscontratos", path: "/convenios/rptadeudoscontratos", displayName: "Rptadeudoscontratos" },
  { name: "rptadeudosconvdiversos", path: "/convenios/rptadeudosconvdiversos", displayName: "Rptadeudosconvdiversos" },
  { name: "rptadeudosconvdiversossaldoant", path: "/convenios/rptadeudosconvdiversossaldoant", displayName: "Rptadeudosconvdiversossaldoant" },
  { name: "rptadeudospredios", path: "/convenios/rptadeudospredios", displayName: "Rptadeudospredios" },
  { name: "rptadeudosprediossaldoant", path: "/convenios/rptadeudosprediossaldoant", displayName: "Rptadeudosprediossaldoant" },
  { name: "rptaltasconvdiv", path: "/convenios/rptaltasconvdiv", displayName: "Rptaltasconvdiv" },
  { name: "rptcalles", path: "/convenios/rptcalles", displayName: "Rptcalles" },
  { name: "rptcaratuladatos", path: "/convenios/rptcaratuladatos", displayName: "Rptcaratuladatos" },
  { name: "rptcolonias", path: "/convenios/rptcolonias", displayName: "Rptcolonias" },
  { name: "rptedocuenta", path: "/convenios/rptedocuenta", displayName: "Rptedocuenta" },
  { name: "rptestadisticascontratos", path: "/convenios/rptestadisticascontratos", displayName: "Rptestadisticascontratos" },
  { name: "rptestadisticasperiodos", path: "/convenios/rptestadisticasperiodos", displayName: "Rptestadisticasperiodos" },
  { name: "rptliquidadosgeneralcol", path: "/convenios/rptliquidadosgeneralcol", displayName: "Rptliquidadosgeneralcol" },
  { name: "rptpagoscapturados", path: "/convenios/rptpagoscapturados", displayName: "Rptpagoscapturados" },
  { name: "rptpagoscontabilidad", path: "/convenios/rptpagoscontabilidad", displayName: "Rptpagoscontabilidad" },
  { name: "rptpagoscontratosdecsdev", path: "/convenios/rptpagoscontratosdecsdev", displayName: "Rptpagoscontratosdecsdev" },
  { name: "rptpagosdesarrollo", path: "/convenios/rptpagosdesarrollo", displayName: "Rptpagosdesarrollo" },
  { name: "rptparcvencidasconvdiversos", path: "/convenios/rptparcvencidasconvdiversos", displayName: "Rptparcvencidasconvdiversos" },
  { name: "rptparcvencidaspredios", path: "/convenios/rptparcvencidaspredios", displayName: "Rptparcvencidaspredios" },
  { name: "rptservicios", path: "/convenios/rptservicios", displayName: "Rptservicios" },
  { name: "servicio", path: "/convenios/servicio", displayName: "Servicio" },
  { name: "serviciosmntto", path: "/convenios/serviciosmntto", displayName: "Serviciosmntto" },
  { name: "sfrm_deudagrupo", path: "/convenios/sfrm_deudagrupo", displayName: "Sfrm Deudagrupo" },
  { name: "simuladorconvenio", path: "/convenios/simuladorconvenio", displayName: "Simuladorconvenio" },
  { name: "subtipo", path: "/convenios/subtipo", displayName: "Subtipo" },
  { name: "subtipomntto", path: "/convenios/subtipomntto", displayName: "Subtipomntto" },
  { name: "tipos", path: "/convenios/tipos", displayName: "Tipos" },
  { name: "tiposmntto", path: "/convenios/tiposmntto", displayName: "Tiposmntto" },
]

export const apremiosRoutes = [
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "SistemaConveniosApremios", path: "/apremios/sistemaconveniosapremios", displayName: "🆕 Sistema Integral de Convenios", isNew: false },
  { name: "SistemaApremiosApremios", path: "/apremios/sistemaapremiosapremios", displayName: "🆕 Sistema Integral de Apremios", isNew: false },
  { name: "SistemaDescuentosApremios", path: "/apremios/sistemadescuentosapremios", displayName: "🆕 Sistema de Descuentos y Conversión", isNew: false },
  // Componentes existentes
  { name: "abcejec", path: "/apremios/abcejec", displayName: "Abcejec" },
  { name: "acceso", path: "/apremios/acceso", displayName: "Acceso" },
  { name: "autorizades", path: "/apremios/autorizades", displayName: "Autorizades" },
  { name: "cartainvitacion", path: "/apremios/cartainvitacion", displayName: "Cartainvitacion" },
  { name: "cmultemision", path: "/apremios/cmultemision", displayName: "Cmultemision" },
  { name: "cmultfolio", path: "/apremios/cmultfolio", displayName: "Cmultfolio" },
  { name: "consultareg", path: "/apremios/consultareg", displayName: "Consultareg" },
  { name: "cons_his", path: "/apremios/cons_his", displayName: "Cons His" },
  { name: "ejecutores", path: "/apremios/ejecutores", displayName: "Ejecutores" },
  { name: "estadxfolio", path: "/apremios/estadxfolio", displayName: "Estadxfolio" },
  { name: "exportarexcel", path: "/apremios/exportarexcel", displayName: "Exportarexcel" },
  { name: "facturacion", path: "/apremios/facturacion", displayName: "Facturacion" },
  { name: "firmaelectronica", path: "/apremios/firmaelectronica", displayName: "Firmaelectronica" },
  { name: "individual", path: "/apremios/individual", displayName: "Individual" },
  { name: "individual_folio", path: "/apremios/individual_folio", displayName: "Individual Folio" },
  { name: "listados", path: "/apremios/listados", displayName: "Listados" },
  { name: "listadosadeaseoform", path: "/apremios/listadosadeaseoform", displayName: "Listadosadeaseoform" },
  { name: "listadosadeexclusivosform", path: "/apremios/listadosadeexclusivosform", displayName: "Listadosadeexclusivosform" },
  { name: "listadosadeinfraccionesform", path: "/apremios/listadosadeinfraccionesform", displayName: "Listadosadeinfraccionesform" },
  { name: "listadosademercadosform", path: "/apremios/listadosademercadosform", displayName: "Listadosademercadosform" },
  { name: "listadosadepublicosform", path: "/apremios/listadosadepublicosform", displayName: "Listadosadepublicosform" },
  { name: "listadossinadereq", path: "/apremios/listadossinadereq", displayName: "Listadossinadereq" },
  { name: "listados_ade", path: "/apremios/listados_ade", displayName: "Listados Ade" },
  { name: "lista_eje", path: "/apremios/lista_eje", displayName: "Lista Eje" },
  { name: "lista_gastoscob", path: "/apremios/lista_gastoscob", displayName: "Lista Gastoscob" },
  { name: "listxfec", path: "/apremios/listxfec", displayName: "Listxfec" },
  { name: "listxreg", path: "/apremios/listxreg", displayName: "Listxreg" },
  { name: "list_eje", path: "/apremios/list_eje", displayName: "List Eje" },
  { name: "menu", path: "/apremios/menu", displayName: "Menu" },
  { name: "modifcar", path: "/apremios/modifcar", displayName: "Modifcar" },
  { name: "modificar_bien", path: "/apremios/modificar_bien", displayName: "Modificar Bien" },
  { name: "modif_masiva", path: "/apremios/modif_masiva", displayName: "Modif Masiva" },
  { name: "modulodb", path: "/apremios/modulodb", displayName: "Modulodb" },
  { name: "notificaciones", path: "/apremios/notificaciones", displayName: "Notificaciones" },
  { name: "notificacionesmes", path: "/apremios/notificacionesmes", displayName: "Notificacionesmes" },
  { name: "prenomina", path: "/apremios/prenomina", displayName: "Prenomina" },
  { name: "reasignacion", path: "/apremios/reasignacion", displayName: "Reasignacion" },
  { name: "recuperacion", path: "/apremios/recuperacion", displayName: "Recuperacion" },
  { name: "reportautor", path: "/apremios/reportautor", displayName: "Reportautor" },
  { name: "requerimientos", path: "/apremios/requerimientos", displayName: "Requerimientos" },
  { name: "rprtcatal_eje", path: "/apremios/rprtcatal_eje", displayName: "Rprtcatal Eje" },
  { name: "rprtestadxfolio", path: "/apremios/rprtestadxfolio", displayName: "Rprtestadxfolio" },
  { name: "rprtlistados", path: "/apremios/rprtlistados", displayName: "Rprtlistados" },
  { name: "rprtlistaxfec", path: "/apremios/rprtlistaxfec", displayName: "Rprtlistaxfec" },
  { name: "rprtlistaxregaseo", path: "/apremios/rprtlistaxregaseo", displayName: "Rprtlistaxregaseo" },
  { name: "rprtlistaxregestacionometro", path: "/apremios/rprtlistaxregestacionometro", displayName: "Rprtlistaxregestacionometro" },
  { name: "rprtlistaxregmer", path: "/apremios/rprtlistaxregmer", displayName: "Rprtlistaxregmer" },
  { name: "rprtlist_eje", path: "/apremios/rprtlist_eje", displayName: "Rprtlist Eje" },
  { name: "rptfact_merc", path: "/apremios/rptfact_merc", displayName: "Rptfact Merc" },
  { name: "rptlistado_aseo", path: "/apremios/rptlistado_aseo", displayName: "Rptlistado Aseo" },
  { name: "rptlistaxregpub", path: "/apremios/rptlistaxregpub", displayName: "Rptlistaxregpub" },
  { name: "rptlista_mercados", path: "/apremios/rptlista_mercados", displayName: "Rptlista Mercados" },
  { name: "rptprenomina", path: "/apremios/rptprenomina", displayName: "Rptprenomina" },
  { name: "rptrecup_aseo", path: "/apremios/rptrecup_aseo", displayName: "Rptrecup Aseo" },
  { name: "rptrecup_merc", path: "/apremios/rptrecup_merc", displayName: "Rptrecup Merc" },
  { name: "rptreq_aseo", path: "/apremios/rptreq_aseo", displayName: "Rptreq Aseo" },
  { name: "rptreq_merc", path: "/apremios/rptreq_merc", displayName: "Rptreq Merc" },
  { name: "rptreq_pba", path: "/apremios/rptreq_pba", displayName: "Rptreq Pba" },
  { name: "rptreq_pba_aseo", path: "/apremios/rptreq_pba_aseo", displayName: "Rptreq Pba Aseo" },
  { name: "sfrm_chgpass", path: "/apremios/sfrm_chgpass", displayName: "Sfrm Chgpass" },
  { name: "unit9", path: "/apremios/unit9", displayName: "Unit9" },
]

export const licenciasRoutes = [
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "PerfilesUsuarioModerno", path: "/licencias/perfilesusuariomoderno", displayName: "🆕 Perfiles Usuario Modernos", isNew: false },
  { name: "CatalogoGirosImportes", path: "/licencias/catalogogirosimportes", displayName: "🆕 Giros con Importes", isNew: false },
  { name: "PermisosProvisionales", path: "/licencias/permisosprovisionales", displayName: "🆕 Permisos Provisionales", isNew: false },
  { name: "SistemaConvenios", path: "/licencias/sistemaconvenios", displayName: "🆕 Sistema Convenios", isNew: false },
  // Componentes existentes
  { name: "Agendavisitasfrm", path: "/licencias/agendavisitasfrm", displayName: "* Agenda Visitas" },
  { name: "bajaAnunciofrm", path: "/licencias/bajaanunciofrm", displayName: "* Baja Anuncios" },
  { name: "bajalicenciafrm", path: "/licencias/bajalicenciafrm", displayName: "* Baja Licencias" },
  { name: "BloquearAnunciorm", path: "/licencias/BloquearAnunciorm", displayName: "* Bloquear Anuncios" },
  { name: "bloqueoDomiciliosfrm", path: "/licencias/bloqueoDomiciliosfrm", displayName: "* Bloqueo Domicilios" },
  { name: "bloqueoRFCfrm", path: "/licencias/bloqueoRFCfrm", displayName: "* Bloqueo RFC" },
  { name: "bloquearlicenciafrm", path: "/licencias/bloquearlicenciafrm", displayName: "* Bloquear Licencias" },
  { name: "BloquearTramitefrm", path: "/licencias/BloquearTramitefrm", displayName: "* Bloquear Trámites" },
  { name: "buscagirofrm", path: "/licencias/buscagirofrm", displayName: "Buscar Giros" },
  { name: "busque", path: "/licencias/busque", displayName: "Búsqueda General" },
  { name: "BusquedaActividadFrm", path: "/licencias/BusquedaActividadFrm", displayName: "* Búsqueda Actividades" },
  { name: "BusquedaScianFrm", path: "/licencias/BusquedaScianFrm", displayName: "* Búsqueda SCIAN" },
  { name: "cancelaTramitefrm", path: "/licencias/cancelaTramitefrm", displayName: "Cancelar Trámites" },
  { name: "carga", path: "/licencias/carga", displayName: "Carga Cobertura" },
  { name: "cargadatosfrm", path: "/licencias/cargadatosfrm", displayName: "Carga Datos" },
  { name: "carga_imagen", path: "/licencias/carga_imagen", displayName: "Carga Imágenes" },
  { name: "cartonva", path: "/licencias/cartonva", displayName: "Cartón VA" },
  { name: "CatalogoActividadesFrm", path: "/licencias/CatalogoActividadesFrm", displayName: "Catálogo Actividades" },
  { name: "catalogogirosfrm", path: "/licencias/catalogogirosfrm", displayName: "Catálogo Giros" },
  { name: "CatRequisitos", path: "/licencias/CatRequisitos", displayName: "Catálogo Requisitos" },
  { name: "catastrodm", path: "/licencias/catastrodm", displayName: "Catastro DM" },
  { name: "certificacionesfrm", path: "/licencias/certificacionesfrm", displayName: "Certificaciones" },
  { name: "consAnun400frm", path: "/licencias/consAnun400frm", displayName: "Consulta Anuncios 400 *" },
  { name: "consultaAnunciofrm", path: "/licencias/consultaAnunciofrm", displayName: "Consulta Anuncios *" },
  { name: "consultaLicenciafrm", path: "/licencias/consultaLicenciafrm", displayName: "Consulta Licencias *" },
  { name: "consLic400frm", path: "/licencias/conslic400frm", displayName: "Consulta Licencia 400 *" },
  { name: "consultapredial", path: "/licencias/consultapredial", displayName: "Consulta Predial *" },
  { name: "ConsultaTramitefrm", path: "/licencias/ConsultaTramitefrm", displayName: "Consulta Trámites *" },
  { name: "consultausuariosfrm", path: "/licencias/consultausuariosfrm", displayName: "Consulta Usuarios *" },
  { name: "constanciafrm", path: "/licencias/constanciafrm", displayName: "Constancias *" },
  { name: "constanciaNoOficialfrm", path: "/licencias/constanciaNoOficialfrm", displayName: "Constancias No Oficiales *" },
  { name: "Cruces", path: "/licencias/Cruces", displayName: "Cruces *" },
  { name: "dependenciasFrm", path: "/licencias/dependenciasFrm", displayName: "Dependencias *" },
  { name: "dictamenfrm", path: "/licencias/dictamenfrm", displayName: "Dictámenes *" },
  { name: "dictamenusodesuelo", path: "/licencias/dictamenusodesuelo", displayName: "Dictamen Uso de Suelo *" },
  { name: "doctosfrm", path: "/licencias/doctosfrm", displayName: "Documentos *" },
  { name: "empleadoslistado", path: "/licencias/empleadoslistado", displayName: "Empleados *" },
  { name: "empresasfrm", path: "/licencias/empresasfrm", displayName: "Empresas *" },
  { name: "estatusfrm", path: "/licencias/estatusfrm", displayName: "Estatus *" },
  { name: "fechasegfrm", path: "/licencias/fechasegfrm", displayName: "Fecha Seguimiento" },
  { name: "firma", path: "/licencias/firma", displayName: "Firma *" },
  { name: "firmausuario", path: "/licencias/firmausuario", displayName: "Firma Usuario *" },
  { name: "formabuscalle", path: "/licencias/formabuscalle", displayName: "Buscar Calles" },
  { name: "formabuscolonia", path: "/licencias/formabuscolonia", displayName: "Buscar Colonias" },
  { name: "formatosEcologiafrm", path: "/licencias/formatosEcologiafrm", displayName: "Formatos Ecología *" },
  { name: "frmImpLicenciaReglamentada", path: "/licencias/frmImpLicenciaReglamentada", displayName: "Formulario Impresión Licencia" },
  { name: "frmselcalle", path: "/licencias/frmselcalle", displayName: "Seleccionar Calles" },
  { name: "gestionHologramasfrm", path: "/licencias/gestionHologramasfrm", displayName: "Gestión Hologramas *" },
  { name: "GirosDconAdeudofrm", path: "/licencias/GirosDconAdeudofrm", displayName: "Giros con Adeudo *" },
  { name: "girosVigentesCteXgirofrm", path: "/licencias/girosVigentesCteXgirofrm", displayName: "Giros Vigentes por Cliente" },
  { name: "grs_dlg", path: "/licencias/grs_dlg", displayName: "Configuración Sistema" },
  { name: "GruposAnunciosAbcfrm", path: "/licencias/GruposAnunciosAbcfrm", displayName: "Grupos Anuncios ABC" },
  { name: "gruposAnunciosfrm", path: "/licencias/gruposAnunciosfrm", displayName: "Grupos Anuncios" },
  { name: "GruposLicenciasAbcfrm", path: "/licencias/GruposLicenciasAbcfrm", displayName: "Grupos Licencias ABC" },
  { name: "gruposLicenciasfrm", path: "/licencias/gruposLicenciasfrm", displayName: "Grupos Licencias" },
  { name: "Hastafrm", path: "/licencias/Hastafrm", displayName: "Configuración Fechas" },
  { name: "h_bloqueoDomiciliosfrm", path: "/licencias/h_bloqueoDomiciliosfrm", displayName: "Historial Bloqueo Domicilios" },
  { name: "ImpLicenciaReglamentadaFrm", path: "/licencias/ImpLicenciaReglamentadaFrm", displayName: "Imprimir Licencia Reglamentada" },
  { name: "ImpOficiofrm", path: "/licencias/ImpOficiofrm", displayName: "Imprimir Oficios" },
  { name: "ImpRecibofrm", path: "/licencias/ImpRecibofrm", displayName: "Imprimir Recibos" },
  { name: "impsolinspeccionfrm", path: "/licencias/impsolinspeccionfrm", displayName: "Imprimir Solicitud Inspección" },
  { name: "LicenciasVigentesfrm", path: "/licencias/LicenciasVigentesfrm", displayName: "Licencias Vigentes *" },
  { name: "ligaAnunciofrm", path: "/licencias/ligaAnunciofrm", displayName: "Liga Anuncios" },
  { name: "LigaRequisitos", path: "/licencias/LigaRequisitos", displayName: "Liga Requisitos" },
  { name: "modlicAdeudofrm", path: "/licencias/modlicAdeudofrm", displayName: "Modificar Licencias Adeudo" },
  { name: "modlicfrm", path: "/licencias/modlicfrm", displayName: "Modificar Licencias *" },
  { name: "modtramitefrm", path: "/licencias/modtramitefrm", displayName: "Modificar Trámites" },
  { name: "observacionfrm", path: "/licencias/observacionfrm", displayName: "Observaciones" },
  { name: "prepagofrm", path: "/licencias/prepagofrm", displayName: "Prepagos" },
  { name: "privilegios", path: "/licencias/privilegios", displayName: "Privilegios *" },
  { name: "prophologramasfrm", path: "/licencias/prophologramasfrm", displayName: "Propuesta Hologramas" },
  { name: "Propuestatab", path: "/licencias/Propuestatab", displayName: "Propuesta Tab" },
  { name: "psplash", path: "/licencias/psplash", displayName: "Pantalla Splash" },
  { name: "ReactivaTramite", path: "/licencias/ReactivaTramite", displayName: "Reactivar Trámites" },
  { name: "regHfrm", path: "/licencias/regHfrm", displayName: "Registro H" },
  { name: "regsolicfrm", path: "/licencias/regsolicfrm", displayName: "Registro Solicitudes" },
  { name: "regsolicfrm_manual", path: "/licencias/regsolicfrm_manual", displayName: "Registro Manual Solicitudes" },
  { name: "RegistroSolicitudForm", path: "/licencias/RegistroSolicitudForm", displayName: "Formulario Registro Solicitud" },
  { name: "repdoc", path: "/licencias/repdoc", displayName: "Reporte Documentos" },
  { name: "repEstadisticosLicfrm", path: "/licencias/repEstadisticosLicfrm", displayName: "Reportes Estadísticos" },
  { name: "repestado", path: "/licencias/repestado", displayName: "Reporte Estado" },
  { name: "ReporteAnunExcelfrm", path: "/licencias/ReporteAnunExcelfrm", displayName: "Reporte Anuncios Excel" },
  { name: "repsuspendidasfrm", path: "/licencias/repsuspendidasfrm", displayName: "Reporte Suspendidas" },
  { name: "Responsivafrm", path: "/licencias/Responsivafrm", displayName: "Responsivas" },
  { name: "revisionesfrm", path: "/licencias/revisionesfrm", displayName: "Revisiones" },
  { name: "Semaforo", path: "/licencias/Semaforo", displayName: "Semáforo" },
  { name: "sfrm_chgfirma", path: "/licencias/sfrm_chgfirma", displayName: "Cambiar Firma" },
  { name: "sfrm_chgpass", path: "/licencias/sfrm_chgpass", displayName: "Cambiar Password" },
  { name: "splash", path: "/licencias/splash", displayName: "Pantalla Inicio" },
  { name: "tipobloqueofrm", path: "/licencias/tipobloqueofrm", displayName: "Tipos Bloqueo" },
  { name: "TramiteBajaAnun", path: "/licencias/TramiteBajaAnun", displayName: "Trámite Baja Anuncios" },
  { name: "TramiteBajaLic", path: "/licencias/TramiteBajaLic", displayName: "Trámite Baja Licencias" },
  { name: "UnidadImg", path: "/licencias/UnidadImg", displayName: "Unidad Imágenes" },
  { name: "webBrowser", path: "/licencias/webBrowser", displayName: "Navegador Web" },
  { name: "ZonaAnuncio", path: "/licencias/ZonaAnuncio", displayName: "Zona Anuncios" },
  { name: "ZonaLicencia", path: "/licencias/ZonaLicencia", displayName: "Zona Licencias" }
]

export const cementeriosRoutes = [
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "SistemaDescuentosCementerios", path: "/cementerios/sistemadescuentoscementerios", displayName: "🆕 Sistema de Descuentos Automatizados", isNew: false },
  { name: "SistemaConversionRevaluacion", path: "/cementerios/sistemaconversionrevaluacion", displayName: "🆕 Sistema de Conversión y Revaluación", isNew: false },
  { name: "SistemaConsultasUnificadas", path: "/cementerios/sistemaconsultasunificadas", displayName: "🆕 Sistema de Consultas Unificadas", isNew: false },
  { name: "FuncionesExcluidasCementerios", path: "/cementerios/funcionesexcluidascementerios", displayName: "🆕 Funciones Excluidas", isNew: false },

  // COMPONENTES EXISTENTES
  { name: "abcementer", path: "/cementerios/abcementer", displayName: "Abcementer" },
  { name: "abcfolio", path: "/cementerios/abcfolio", displayName: "Abcfolio" },
  { name: "abcpagos", path: "/cementerios/abcpagos", displayName: "Abcpagos" },
  { name: "abcpagosxfol", path: "/cementerios/abcpagosxfol", displayName: "Abcpagosxfol" },
  { name: "abcrecargos", path: "/cementerios/abcrecargos", displayName: "Abcrecargos" },
  { name: "acceso", path: "/cementerios/acceso", displayName: "Acceso" },
  { name: "bonificacion1", path: "/cementerios/bonificacion1", displayName: "Bonificacion1" },
  { name: "bonificaciones", path: "/cementerios/bonificaciones", displayName: "Bonificaciones" },
  { name: "conindividual", path: "/cementerios/conindividual", displayName: "Conindividual" },
  { name: "consulta400", path: "/cementerios/consulta400", displayName: "Consulta400" },
  { name: "consultafol", path: "/cementerios/consultafol", displayName: "Consultafol" },
  { name: "consultaguad", path: "/cementerios/consultaguad", displayName: "Consultaguad" },
  { name: "consultajardin", path: "/cementerios/consultajardin", displayName: "Consultajardin" },
  { name: "consultamezq", path: "/cementerios/consultamezq", displayName: "Consultamezq" },
  { name: "consultanombre", path: "/cementerios/consultanombre", displayName: "Consultanombre" },
  { name: "consultarcm", path: "/cementerios/consultarcm", displayName: "Consultarcm" },
  { name: "consultasandres", path: "/cementerios/consultasandres", displayName: "Consultasandres" },
  { name: "descuentos", path: "/cementerios/descuentos", displayName: "Descuentos" },
  { name: "duplicados", path: "/cementerios/duplicados", displayName: "Duplicados" },
  { name: "estad_adeudo", path: "/cementerios/estad_adeudo", displayName: "Estad Adeudo" },
  { name: "liquidaciones", path: "/cementerios/liquidaciones", displayName: "Liquidaciones" },
  { name: "list_mov", path: "/cementerios/list_mov", displayName: "List Mov" },
  { name: "menu", path: "/cementerios/menu", displayName: "Menu" },
  { name: "modulo", path: "/cementerios/modulo", displayName: "Modulo" },
  { name: "multiplefecha", path: "/cementerios/multiplefecha", displayName: "Multiplefecha" },
  { name: "multiplenombre", path: "/cementerios/multiplenombre", displayName: "Multiplenombre" },
  { name: "multiplercm", path: "/cementerios/multiplercm", displayName: "Multiplercm" },
  { name: "rep_a_cobrar", path: "/cementerios/rep_a_cobrar", displayName: "Rep A Cobrar" },
  { name: "rep_bon", path: "/cementerios/rep_bon", displayName: "Rep Bon" },
  { name: "rpttitulos", path: "/cementerios/rpttitulos", displayName: "Rpttitulos" },
  { name: "sfrm_chgpass", path: "/cementerios/sfrm_chgpass", displayName: "Sfrm Chgpass" },
  { name: "titulos", path: "/cementerios/titulos", displayName: "Titulos" },
  { name: "titulossin", path: "/cementerios/titulossin", displayName: "Titulossin" },
  { name: "trasladofol", path: "/cementerios/trasladofol", displayName: "Trasladofol" },
  { name: "trasladofolsin", path: "/cementerios/trasladofolsin", displayName: "Trasladofolsin" },
  { name: "traslados", path: "/cementerios/traslados", displayName: "Traslados" },
]

export const otrasObligRoutes = [
  // 🆕 NUEVOS COMPONENTES DE MODERNIZACIÓN
  { name: "SistemaConveniosOtrasOblig", path: "/otras-oblig/sistemaconveniosotrasOblig", displayName: "🆕 Sistema Integral de Convenios", isNew: false },
  { name: "SistemaApremiosOtrasOblig", path: "/otras-oblig/sistemaapremiosotrasOblig", displayName: "🆕 Sistema Integral de Apremios", isNew: false },
  { name: "SistemaDescuentosOtrasOblig", path: "/otras-oblig/sistemadescuentosotrasOblig", displayName: "🆕 Sistema de Descuentos y Conversión", isNew: false },
  { name: "FuncionesExcluidasOtrasOblig", path: "/otras-oblig/funcionesexcluidasotrasOblig", displayName: "🆕 Funciones Excluidas", isNew: false },

  // COMPONENTES EXISTENTES
  { name: "apremios", path: "/otras-oblig/apremios", displayName: "Apremios" },
  { name: "gactualiza", path: "/otras-oblig/gactualiza", displayName: "Gactualiza" },
  { name: "gadeudos_opcmult", path: "/otras-oblig/gadeudos_opcmult", displayName: "Gadeudos Opcmult" },
]

export default {
  estacionamientosRoutes,
  aseoRoutes,
  licenciasRoutes,
  mercadosRoutes,
  recaudadoraRoutes,
  tramiteTrunkRoutes,
  conveniosRoutes,
  apremiosRoutes,
  cementeriosRoutes,
  otrasObligRoutes
}
